### ISSUE TITLE
Message does not fit to screen after updating grub

### ISSUE THREAD

**Issue by chri2** [osresearch/heads#1048]
After an update of grub packages on my system ( debian/bullseye aka pureos byzantinum - test of a patched grub-common with 10-linux adapted to respect GRUB_CMDLINE_LINUX_RECOVERY from /etc/default/grub) the checksum of nearly all files under /boot/grub had been changed.

This led to the situation that I couldn't read the whole message in heads and neither the selection whether I'd like to sign the files. (see screenshot below)

I guess this problem could have been solved by @itay-grudev suggestion to have an option to sign changes inside the os when updating or changing files in boot https://github.com/osresearch/heads/issues/533 .

![IMG20211027222940](https://user-images.githubusercontent.com/15866990/139236644-48903fa2-4c32-4fbd-9811-eb7b2bce9819.jpg)

**Comment by tlaurion** [comment]
@chri2 : fixed under master with merged PR above.
If there is more then 10 changes, Heads will now less an output of the changes for review, prompting user to type 'q' to go back at choosing to sign those. You can still go to the recovery and inspect those changes yourself.

Fee free to reopen issue if that doesn't fit your needs.
