### ISSUE TITLE
Qubes version: bump instructions to R3.2

### ISSUE THREAD

**Issue by jonathanfemideer** [osresearch/heads#108]
The instructions at https://trmm.net/Installing_Heads#Installing_Qubes state:

    --module "./vmlinuz inst.stage2=hd:LABEL=Qubes-R3.2-rc3-x86_64 i915.preliminary_hw_support=1" \

However, the current version of Qubes recommended by the Qubes team is [no longer R3.2-rc3, but R3.2](https://www.qubes-os.org/doc/releases/3.2/schedule/).

For users installing Heads from R3.2 installation media, that line above should instead read:

    --module "./vmlinuz inst.stage2=hd:LABEL=Qubes-R3.2-x86_64 i915.preliminary_hw_support=1" \

**Comment by osresearch** [comment]
Updated.  Also included the command to `gunzip /xen-4.6.3.gz` since the `kexec` built in 0.1.0 doesn't have gzip support.
