### ISSUE TITLE
Documentation typo in "Installing Qubes"

### ISSUE THREAD

**Issue by jonathanfemideer** [osresearch/heads#109]
The *Installing Heads* manual's section [Installing Qubes](https://trmm.net/Installing_Heads#Installing_Qubes) has a typo. It says:

> Run /boot/start-xen and kexec -e and wait for the Qubes configuration to finish.

It should say:

> Run <code>/<b>bin</b>/start-xen</code> and `kexec -e` and wait for the Qubes configuration to finish.

**Comment by osresearch** [comment]
You can now fix it in the [Installing Heads](../wiki/Installing-Heads) wiki page, although we'll need to be sure that the `/bin/start-xen` script works.

**Comment by paulmenzel** [comment]
I updated the wiki page, so this issue can be closed.
