### ISSUE TITLE
Heads license is unclear

### ISSUE THREAD

**Issue by jonathanfemideer** [osresearch/heads#115]
Please can a license be chosen and added to the repository?

I think the license would have to be [GPLv2 compatible](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses) because Heads builds include a Linux kernel, but IANAL.

Best of all would to license Heads under AGPLv3+ or at least GPLv3+, to maximize the chance of downstream improvements being made available to the community, for integration upstream.

**Comment by osresearch** [comment]
Since most of the components are GPLv2 (Linux, busybox, coreboot, etc), GPL makes the most sense.  I've added the `COPYING` file.
