### ISSUE TITLE
default build target is qemu, not qemu and x230

### ISSUE THREAD

**Issue by mfc** [osresearch/heads#118]
probably should be both or just x230? or make more clear in documentation for user to change this in `Makefile`

**Comment by jonathanfemideer** [comment]
Might be safer to leave Qemu as the default, to encourage users to test the Qemu build first?

**Comment by osresearch** [comment]
Alternatively we could have no default target and print some help text when the user runs `make`.

**Comment by osresearch** [comment]
I've written some documentation on [building Heads](http://osresearch.net/Building) with some background on the different targets.
