### ISSUE TITLE
W530 t530 t520 @wiki

### ISSUE THREAD

**Issue by 3hhh** [osresearch/heads#1186]
I noticed that W530 t530 t520 apparently [are supported](https://github.com/osresearch/heads/pull/1074) by heads. :-)

However the [wiki indicates that they are not](https://github.com/osresearch/heads-wiki/blob/master/Installing-and-Configuring/Prerequisites.md).
I guess it needs updating?

**Comment by tlaurion** [comment]
@3hhh yes to all to above.

Documentation is scattered in PR created by @eganonoa and would need someone to take the lead to create guides related to disassembling and flashing.

A discussion is happening under https://forum.qubes-os.org/t/request-for-advice-to-install-coreboot-heads-on-thinkpad-w530/12301/9

Will crosslink here, hopefully for collaboration in creating the docs

**Comment by tlaurion** [comment]
Documentation issues should happen under heads-wiki though. Issues related to Heads code should happen here.

**Comment by tlaurion** [comment]
Issue already opened under https://github.com/osresearch/heads-wiki/issues/83
