### ISSUE TITLE
Severe performance issues with 32GB RAM, but works fine with 16GB. W530

### ISSUE THREAD

**Issue by Sirwhofromwhere** [osresearch/heads#1187]
**What I run**

Latest HEADS w530-hotp-k1000m-maximized on a W530 i7-3840QM with updated Qubes. 

Ram module specification: 8GB SP 1600mhz ddr3l

**The issue**

Internal motherboard RAM slots causing serious performance issues to where 32GB of RAM is critically slow, yet 16GB of ram in the external RAM slots works fine.

**Troubleshooting done**

Tested both 2x4GB and now the full 4x8GB RAM in the laptop with memtest64, running 8+ passes on each without error. 
Tested original 2x8GB RAM in the internal ram modules, immediate errors returned. Tested on external slots and worked fine.

To note, I created a previous issue here that ultimately turned out to be due to using my 2x8GB RAM in the internal slots during installation and use. When I ran memtest on those specific RAM modules (2x8GB SP 1600) in the internal motherboard slots I would get immediate and voluminous errors, whereas running them in the external RAM slots would return none over many passes.

To test if it was an error with the slots, I ran 2x4GB and the full 32GB ram through many passes of memtest and had no errors returned. So one set of the SP ram returned immediate errors from the internal slots, but the other two did not, and since relocating the original pair of 8GB ram modules to the external slots performance was great.

When I boot the full 32GB of RAM I get slower boot times and critically impacted performance, not crashing however. When I rebooted with just the original 2x8GB ram in the external slots, the performance was still bad, but after another reboot it had returned to as expected performance, which I found odd. This was not repeated on my second attempt to run 32GB and then switch back.

When I run a memtest on the **new** RAM modules (2x8GB) in the internal motherboard RAM slots, I get no issues on many memtest passes.

What I'd like to know are some reasonable troubleshooting methods I can make to understand why 32GB of working RAM would be causing such issues, and also how HEADS might be affecting the RAM. 

 **Thank you greatly for any and all assistance.**

**Comment by tlaurion** [comment]
@Sirwhofromwhere what are your

> get slower boot times and critically impacted performance ?

Do you get errors from dom0 with `sudo dmesg` ?

@walliams @eganonoa (owners of w530) do you see lower performances with 32gb ram?

**Comment by tlaurion** [comment]
Qubes has this opened issue https://github.com/QubesOS/qubes-issues/issues/7404

**Comment by tlaurion** [comment]
The next step, if I understand well, might be to test a good external slot memory to internal slot. And isolate which internal slot is problematic.

Reading the above I'm still not clear which ones of the internal slot would be faulty or if one memory stick is at cause?

**Comment by Sirwhofromwhere** [comment]
@tlaurion I've now run three different sets of RAM through the internal slots with immediate failures in the slot. One 4GB RAM stick, one 8GB SP, and another separate batch 8GB SP.

Seems like it must be the slot that is at fault, as those memory sticks work fine in the external slots. Very bizarre, but nothing I can do about it as I think getting the memory slot replaced might be prohibitively expensive, as will buying a new motherboard.

I tried both slots before individually with one stick of the 8GB RAM and both failed, just one failed slower. I'll try again to see if I can isolate a slot, but I believe both are at fault.

Thanks for your efforts in helping me.

**Comment by Sirwhofromwhere** [comment]
Closing due to isolating issue to the internal RAM slot or other motherboard fault.
