### ISSUE TITLE
Some issues discovered with whiptail output (BMC tested: smaller screen)

### ISSUE THREAD

**Issue by tlaurion** [osresearch/heads#1237]
Some tests conducted on https://github.com/osresearch/heads/tree/1cb0324a12aa4aec01287142c76b5a41ed51a2cb

Whiptail can fixate (optional) the size of its windows with calls of Height x Width.
As of now on master, it's 30 x 90, where 90 is too wide for BMC output. This causes some issues.
Also, some output is considered to be of a static height, causing issues as well.

It is understandable to want to have fixated Height x Width to have consistent UX through menus, but that should not cause bogus output.

-------------------
Main menu (gui-init's show_main_menu function):

30x90
![2022-11-08-133047](https://user-images.githubusercontent.com/827570/200660936-f9763ff5-2571-431b-a6ef-8c30e8050a26.png)

30x80
![2022-11-08-150634](https://user-images.githubusercontent.com/827570/200664510-c7da4aa2-9350-49b8-8859-49b660270e9d.png)

20x80:
![2022-11-08-144920](https://user-images.githubusercontent.com/827570/200661188-294f3d21-e02a-4d7f-ad17-1ba3274cc1d4.png)

0x80:
![2022-11-08-150908](https://user-images.githubusercontent.com/827570/200664959-c7d3ec15-88b7-4b0f-a8f0-d652d3b7a1c0.png)

0x0
![2022-11-08-150808](https://user-images.githubusercontent.com/827570/200664796-dcab76b6-8ed7-47a9-b3cf-6caff6c75292.png)

------------
Some menus just don't show properly without proper selections, as seen above, but also can hide option boxes:

Here, tampered with a single kexec_hashes.txt entree and selecting default boot option.
This happens under gui-init's verify_global_hashes:

30x90:
![2022-11-08-151802](https://user-images.githubusercontent.com/827570/200666722-ebd83533-85ba-4c12-be43-95224c14eca3.png)

30x80:
  ![2022-11-08-151445](https://user-images.githubusercontent.com/827570/200666104-d87d9680-e607-4838-8add-2ac47afa9954.png)
  
  20x80:
  ![2022-11-08-151940](https://user-images.githubusercontent.com/827570/200666913-1b41923a-8181-4ef9-bcf1-e69ff9c4cc05.png)

0x80
![2022-11-08-152047](https://user-images.githubusercontent.com/827570/200667106-1812cf22-6a58-4107-9d3e-59342e658806.png)

**Comment by tlaurion** [comment]
Attempted to pass vga=795 without change in behavior.
As of now setting 20x80 instead of 30x90 everywhere fixes it.

**Comment by tlaurion** [comment]
Here, tampered with  9 entrees under kexec_hashes.txt entries and selecting default boot option.
This happens under gui-init's verify_global_hashes

30x90:
![2022-11-08-164801](https://user-images.githubusercontent.com/827570/200682908-0066a5d9-087b-48f9-b1cb-abe4bf8df2d2.png)



20x80
![2022-11-08-162752](https://user-images.githubusercontent.com/827570/200679248-1c76f1f8-bf17-42f9-ab17-b80db232aca1.png)

**Comment by tlaurion** [comment]
But unfortunately, not everything fits under 20x90.

One of those is oem-factory-reset script:
![2022-11-08-164927](https://user-images.githubusercontent.com/827570/200683187-433f3067-898d-41cd-9fea-6bddddae2ba0.png)


I'll continue to try to find a way to increase ast2500 console settings.
@JonathonHall-Purism @SergiiDmytruk any idea?  passing `vga=795` to kernel was actually passed but didn't change a thing.

**Comment by tlaurion** [comment]
But then, if I pass 
0x90: 
![2022-11-08-170859](https://user-images.githubusercontent.com/827570/200686405-481f2c7e-2ce1-4a9b-a731-b670f2fa0adc.png)

If I pass 0x0:
![2022-11-08-170935](https://user-images.githubusercontent.com/827570/200686511-7bf2969a-1b18-46f2-a633-3202c416adcd.png)


So @JonathonHall-Purism I understand fixating 80 (the width to minimal display size) or maybe configure it under board configs.
But I think the height maybe should be dynamic?

**Comment by JonathonHall-Purism** [comment]
Definitely agree with dynamic height.  It doesn't make sense to leave those small prompts swimming in empty space, especially for short yes/no where the prompt and selections are separated by a lot of blank lines.

Re: width, just from having looked at the above, I actually like the dynamic width.  It looks like all our prompts have hard line breaks anyway to accommodate fbwhiptail, so I think the dynamic width looks best.  The main boot menu in particular looks better without a bunch of extra whitespace, IMO.  I don't think there is a UX consistency issue (on the contrary, I think it is easier to read at a glance).

But otherwise, I'd say to fix it globally to 80, not make it board-specific.  IMO being able to raise the width per board is not that useful right now since the prompts need hard line breaks for fbwhiptail anyway.

**Comment by tlaurion** [comment]
@JonathonHall-Purism there is some place in code that are using busybox's "fold" for long strings, without having to fuss around into manipulating strings to match constant width. From my succing tests, I haven't seen any regression in GUIs setting the width to 80.

Will push PR soon to set width to 80 and height to 0 (dynamic).

**Comment by tlaurion** [comment]
Ok, testing those on talos II where artifacts under https://app.circleci.com/pipelines/github/tlaurion/heads/1253/workflows/08e0593b-1726-4af7-a7f5-059c740bdef2/jobs/11935/artifacts were flashed.

Which are linked to talos II specific : https://github.com/tlaurion/heads/tree/SergiiDmytruk_flashrom_fff474a_9bb6be887457a3cb28ac831c1547a33752429184

And branch on top of master https://github.com/tlaurion/heads/tree/whiptail_dynamic_height_fixated_width_to_80

-------

Some output with 0x80 over BMC:


![2022-11-09-133801](https://user-images.githubusercontent.com/827570/200915212-ba0df702-d931-49e0-b4b0-796475a8d5f7.png)
![2022-11-09-133816](https://user-images.githubusercontent.com/827570/200915228-d125a26a-ac57-46d1-845c-580a3f9d8d88.png)
![2022-11-09-133832](https://user-images.githubusercontent.com/827570/200915242-6ed52b31-8905-4117-93fa-1463309d75ed.png)
![2022-11-09-133850](https://user-images.githubusercontent.com/827570/200915249-77354aa3-df98-4463-b498-4ebbacca5ea4.png)
![2022-11-09-133947](https://user-images.githubusercontent.com/827570/200915270-417e718f-1f20-480a-981c-94fc1ecfaea9.png)
![2022-11-09-134007](https://user-images.githubusercontent.com/827570/200915281-61f792ea-0964-40ea-af8f-831068768fc3.png)
![2022-11-09-134027](https://user-images.githubusercontent.com/827570/200915293-be7a931f-7d84-46b6-a257-35eeea4efb61.png)
