### ISSUE TITLE
USB boot to PureOS installer shows boot options that don't work

### ISSUE THREAD

**Issue by JonathonHall-Purism** [osresearch/heads#1239]
When booting to a PureOS installer on USB, Heads shows some options that always fail when selected.

Two of the options have `($root)` in them (a variable).  We could safely ignore these (they're the EFI boot options, and the BIOS boot options are fine), but some code in `kexec-parse-boot` makes me think it is actually trying to expand variables, so I can't just ignore any boot options containing variables:

```
		echo $(eval "echo \"$entry\"")
```

@tlaurion Is there any reason to keep any boot options with variables in them?  I checked a handful of ISOs and have not found any (Debian live, Fedora live, Qubes installer, although there are tons more...).

**Comment by tlaurion** [comment]
@JonathonHall-Purism no! Propose anything!

**Comment by tlaurion** [comment]
Related https://github.com/osresearch/heads/issues/1001#issuecomment-1159640544

**Comment by JonathonHall-Purism** [comment]
Cool, I will get a PR up.  It looks like it also picks up a memtest image that doesn't work either, hmm, looking into some way to identify that

**Comment by tlaurion** [comment]
Memtest can be booted from latest beta image from memtest, look at separate the solved issue for instructions
