### ISSUE TITLE
Allow to pass the number of jobs to build in parallel

### ISSUE THREAD

**Issue by paulmenzel** [osresearch/heads#125]
Currently eight jobs seems to be hard coded in a lot of places, and no way is specified how to set another number of jobs.

**Comment by osresearch** [comment]
I'd also like to track down how to build the entire system in parallel; many of the `foo.intermediate` targets do not depend on each other, so once the cross compiler is built it seems that we should be able to build kexec, lvm, tpm, etc simultaneously.  Even the Linux kernel, if we can figure out why coreboot isn't correctly linking in the `initrd.cpio.xz` when it is specified in the coreboot `.config` file (it worked sometime in the 4.4 era, I believe).
