### ISSUE TITLE
Boot Error into Boot-able Boot-and-Nuke Software

### ISSUE THREAD

**Issue by newbieAtGithub** [osresearch/heads#1279]
hi @tlaurion 

Please kindly help with below error,

Boards: x230-maximized + Yubikey
1st time flash, self installed, external flash, IFD unlocked, downloaded from Circle CI, 

Steps to reproduce: 

First, plugin USB device, containing boot-able boot-and-nuke software, [Aban](https://aban.derobert.net/),
Second, turn on Heads laptop, & navigate to boot options > USB boot > Aban, like below screenshot: 

![1](https://user-images.githubusercontent.com/119822432/212534324-43b23770-eec3-41a2-8b34-51c9cc5b6994.jpg)

Third, choose Aban disk wiper

![2](https://user-images.githubusercontent.com/119822432/212534388-f7041e67-6a11-4ef8-852a-761fa0c7b23a.jpg)

Fourth, then 1st failure happen here "fail to identify", like below screenshot, 
the system stuck at this screen for around 2-3 minutes. 

![3](https://user-images.githubusercontent.com/119822432/212534492-ac33243f-16f3-46cc-8725-42eeb20f3ae9.jpg)

Fifth, then after some time, finally boot failed, like below screenshot,

![4](https://user-images.githubusercontent.com/119822432/212534650-83fe6689-30c1-45f3-99f7-01a67f54d2b8.jpg)

Sixth, reboot the laptop, & navigate to another boot option, like below screenshot,

![5](https://user-images.githubusercontent.com/119822432/212534732-1289e1d7-c706-4d45-a37e-891ebc6f2582.jpg)

Seventh, after choosing the boot option, then the process stuck here, "starting new kernel", 
wait for long time, maybe 5-10 minutes, but nothing happen. 

![6](https://user-images.githubusercontent.com/119822432/212534833-461ebd72-7c02-4a14-a654-9b4f003e1f0d.jpg)

Expectation: boot successfully to [Aban](https://aban.derobert.net/), and wiping HD. 

Thanks and Regards,

**Comment by tlaurion** [comment]
Downloading https://aban.derobert.net/dl/ABAN-amd64.hybrid.iso

@newbieAtGithub 
Pertinent errors should be found under reported screenshot:


building Qemu and injecting key (following instructions to test Heads without hardware on a provisioned debian-11-xcfe OS):
`user@heads-tests:~/heads$ make BOARD=qemu-coreboot-fbwhiptail-tpm1 PUBKEY_ASC=~/QubesIncoming/Insurgo/Insurgo_2023_pub.asc USB_TOKEN=NitrokeyStorage ROOT_DISK_IMG=~/heads/build/x86/qemu-coreboot-fbwhiptail-tpm1-hotp/root.qcow2 inject_gpg`

Using qemu-image tools to take a snapshot prior of trying to use a wiper tool and making sure snapshot exists:
```
user@heads-tests:~/heads$ qemu-img snapshot ~/heads/build/x86/qemu-coreboot-fbwhiptail-tpm1-hotp/root.qcow2 -c working
user@heads-tests:~/heads$ qemu-img snapshot ~/heads/build/x86/qemu-coreboot-fbwhiptail-tpm1-hotp/root.qcow2 -l
Snapshot list:
ID        TAG               VM SIZE                DATE     VM CLOCK     ICOUNT
1         working               0 B 2023-01-16 15:41:50 00:00:00.000          0
```

Launching iso with provisioned disk from qemu doc:
`make BOARD=qemu-coreboot-fbwhiptail-tpm1 PUBKEY_ASC=~/QubesIncoming/Insurgo/Insurgo_2023_pub.asc USB_TOKEN=NitrokeyStorage ROOT_DISK_IMG=~/heads/build/x86/qemu-coreboot-fbwhiptail-tpm1-hotp/root.qcow2 INSTALL_IMG=~/Downloads/ABAN-amd64.hybrid.iso run`

Booting from USB up to ABAN on QEMU board (no hardware)
![2023-01-16-154540](https://user-images.githubusercontent.com/827570/212763798-5691590f-78dc-48a2-97b1-bf144cbc4675.png)
![2023-01-16-154608](https://user-images.githubusercontent.com/827570/212763796-e16bdb5f-52f6-457f-b4b8-545a52ad26fa.png)
![2023-01-16-154631](https://user-images.githubusercontent.com/827570/212763794-c7a62d2d-bbcd-4acc-8a5f-eaab71456718.png)
![2023-01-16-154641](https://user-images.githubusercontent.com/827570/212763791-dfa1ddec-4725-484e-8ca5-e81f4136e560.png)
![2023-01-16-154651](https://user-images.githubusercontent.com/827570/212763789-06b495a6-9378-476f-8df4-9c8e7aa07822.png)
![2023-01-16-154945](https://user-images.githubusercontent.com/827570/212763786-9cc72cae-5fd2-46d1-8468-a95583cf9735.png)
![2023-01-16-155007](https://user-images.githubusercontent.com/827570/212763782-ae19a3a3-0871-4571-8c05-14022aa86fff.png)
![2023-01-16-155028](https://user-images.githubusercontent.com/827570/212763780-8ceb824c-a6e0-4461-a410-c42df095138b.png)


I could not replicate on Qemu.
@newbieAtGithub you are 


> Fifth, then after some time, finally boot failed, like below screenshot,
> 
> ![4](https://user-images.githubusercontent.com/119822432/212534650-83fe6689-30c1-45f3-99f7-01a67f54d2b8.jpg)

What does `cat /boot.log` provides here? What is the platform you are testing (x230?)

**Comment by tlaurion** [comment]
So we know Heads is able to kexec into ABAN from Qemu testing.

Redoing for:
> Boards: x230-maximized + Yubikey


Before inserting USB thumb drive I will overwrite with ABAN iso content:
```
user@heads-tests:~/heads$ lsblk
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
xvda    202:0    1    15G  0 disk 
├─xvda1 202:1    1   200M  0 part 
├─xvda2 202:2    1     2M  0 part 
└─xvda3 202:3    1  14.8G  0 part /
xvdb    202:16   1   100G  0 disk /rw
xvdc    202:32   1    10G  0 disk 
├─xvdc1 202:33   1     1G  0 part [SWAP]
└─xvdc3 202:35   1     9G  0 part 
xvdd    202:48   1 467.5M  1 disk 

```
After inserting USB thumb drive (Qubes OS passing device to qube):
```
user@heads-tests:~/heads$ lsblk
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda       8:0    1  14.8G  0 disk 
└─sda1    8:1    1     8G  0 part 
xvda    202:0    1    15G  0 disk 
├─xvda1 202:1    1   200M  0 part 
├─xvda2 202:2    1     2M  0 part 
└─xvda3 202:3    1  14.8G  0 part /
xvdb    202:16   1   100G  0 disk /rw
xvdc    202:32   1    10G  0 disk 
├─xvdc1 202:33   1     1G  0 part [SWAP]
└─xvdc3 202:35   1     9G  0 part 
xvdd    202:48   1 467.5M  1 disk
```

Inserted device is sda.

dd'ing ISO to thumb drive (iso confirmed working from Qemu, please verify checksum prior which could be be source of error):
```
user@heads-tests:~/heads$ sudo dd if=~/Downloads/ABAN-amd64.hybrid.iso of=/dev/sda bs=16M  status=progress
279969792 bytes (280 MB, 267 MiB) copied, 10 s, 27.0 MB/s
16+1 records in
16+1 records out
279969792 bytes (280 MB, 267 MiB) copied, 29.5348 s, 9.5 MB/s
```

Then redoing USB boot from above option `ABAN_Disk_wiper_amd64` with SSD drive I don't care about its content:
![signal-2023-01-16-164456](https://user-images.githubusercontent.com/827570/212770263-3ba3dd7d-d68a-43c1-914b-b78541713b30.jpeg)
![signal-2023-01-16-164317](https://user-images.githubusercontent.com/827570/212770267-7ad66caf-1609-4175-b1e1-db16ed5d51e9.jpeg)
![signal-2023-01-16-164306](https://user-images.githubusercontent.com/827570/212770268-4ed49c05-c109-419e-b179-2b9438955407.jpeg)

Works perfectly on x230-maximized from master with downloaded ISO: https://aban.derobert.net/dl/ABAN-amd64.hybrid.iso
```
user@heads-tests:~/heads$ sha256sum ~/Downloads/ABAN-amd64.hybrid.iso
6381be3b8a3e8d1e0add9130e8011fd8cb7262a17bb369e240e9352d4d74bff4  /home/user/Downloads/ABAN-amd64.hybrid.iso
```
 
@newbieAtGithub : Hypothesis is corrupted ISO. Please verify checksums and reopen if you consider this was closed by error.

**Comment by tlaurion** [comment]
> Fourth, then 1st failure happen here "fail to identify", like below screenshot, the system stuck at this screen for around 2-3 minutes.
> 
> ![3](https://user-images.githubusercontent.com/119822432/212534492-ac33243f-16f3-46cc-8725-42eeb20f3ae9.jpg)
> 
> Fifth, then after some time, finally boot failed, like below screenshot,
> 
> ![4](https://user-images.githubusercontent.com/119822432/212534650-83fe6689-30c1-45f3-99f7-01a67f54d2b8.jpg)

You seem to have issues with your disk.
`I/O error` are generally not a good thing to see.

**Comment by tlaurion** [comment]
Not related to Heads booting problem but related to that specific drive to wipe issues. Try another drive!

**Comment by newbieAtGithub** [comment]
hi @tlaurion 

i know which part was wrong, Heads failed to boot into ABAN before, 
because i used i386 ISO, instead of amd64 ISO, 
assuming that amd64 is only for AMD processor, while i use Intel, 
but i386 ISO is for 32 bit processor, while mine is 64 bit,
finally i tried amd64 ISO, and it works, thanks. 
because i see above, that you also use amd64, while i guess yours also Intel. 

okay, thanks and regards,
