### ISSUE TITLE
Possible typo in qemu-coreboot-[fb]whiptail-tpm1-hotp.md heading

### ISSUE THREAD

**Issue by cpick** [osresearch/heads#1314]
The heading of the following file (and the non-fb-version) says "whiptal" when the rest of the document says "whiptail" (with an 'i'):
https://github.com/osresearch/heads/blob/ffd8ab9ac537284f99eaa03b171d573623ef8f3b/boards/qemu-coreboot-fbwhiptail-tpm1-hotp/qemu-coreboot-fbwhiptail-tpm1-hotp.md?plain=1#L1

**Comment by tlaurion** [comment]
@cpick nice catch, thanks. Fixed!
