### ISSUE TITLE
Tiny Core Linux ISO: Failed to parse any boot options

### ISSUE THREAD

**Issue by saper** [osresearch/heads#1347]
**Is your feature request related to a problem? Please describe.**

Booting from recovery shell:

Trying to boot http://www.tinycorelinux.net/13.x/x86/release/TinyCore-13.1.iso (md5: df0dc3e39d2b7748a2839bab1ffbd220) via `media-scan /dev/sda1` on X230. I have signed it myself with my GPG key.

After `+++ Mounting ISO and booting`  I get `PCR[4]` update and then `+++Scanning for unsigned boot options` which ends up with

    Failed to parse any boot options

**Describe the solution you'd like**

The system should start.

**Describe alternatives you've considered**

I have unpacked the ISO and added `vmlinuz` and `core.gz` to the `kexec_menu.txt` and re-signed everything to make it work (it still does not fully work, but this is probably not a heads problem, but at least I am getting a working shell).

**Comment by tlaurion** [comment]
Tested against http://www.tinycorelinux.net/13.x/x86/release/TinyCore-13.1.iso on 4.14 kernel and it boots correctly.

(Doesn't on 5.10 test kernel though)

**Comment by tlaurion** [comment]
Also this is syslinux, not grub entries. Digging into grub for the moment.

**Comment by tlaurion** [comment]
Basically, this is isolinux parsing eating /boot/boot into /boot

**Comment by tlaurion** [comment]
@saper https://github.com/osresearch/heads/pull/1377/commits/3af5cf269a24baf486f1b1813e618815cd7002ea fixes it

I created duplicate issue #1374 with unclean pr #1377.
