### ISSUE TITLE
Merge MOC and master Linux config, measure loaded modules

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#139]
The main differences are the use of the networking drivers.  These should be build as modules and measured/loadable at runtime rather than requiring compile time decisions.

**Comment by osresearch** [comment]
Modules are huge and blow out our space budget.  How do we strip them?

**Comment by osresearch** [comment]
`strip --strip-debug` seems to be safe.

**Comment by rofl0r** [comment]
did you consider building the modules statically into the kernel ? i.e. `=y` instead of `=m`.
we do that in sabotage and it simplifies the startup and increases robustness.

**Comment by osresearch** [comment]
Right now they are statically compiled into the kernel, but for security reasons we want to make the modules loadable.  This reduces the attack surface if the network device is not brought online during boot, or if there is no way to attach a USB storage device during the boot process.  Having the modules loadable, but measured, makes it possible to be flexible during setup and recovery stages, while not also having those boundaries exposed.

**Comment by rofl0r** [comment]
good point, that makes sense.

**Comment by osresearch** [comment]
Everything is a module now, I think we're clear to merge the branches.  The MOC branch will continue to iterate on their `initrd/init` script.

**Comment by osresearch** [comment]
https://github.com/osresearch/heads/commit/8343130e9ae3b02045cd430664eb2db06d104de1
