### ISSUE TITLE
Heads needs a bootsplash and a logo!

### ISSUE THREAD

**Issue by tlaurion** [osresearch/heads#1402]
Someone has a proposition for a Heads logo and a bootsplash?

As per https://github.com/osresearch/heads/pull/1381#issuecomment-1542610357 picture:
![signal-2023-05-10-142807_003](https://github.com/osresearch/heads/assets/827570/f3742ee4-78bb-4c74-b1ea-02d5dc7c06d7)

Now could be a great time to combine concepts.
What I have in mind is advertising linuxboot (as a concept) with coreboot (propeller of OSF) and Heads (which misses a logo currently).

Any propositions?

Today's limitation:
- Logo needs to be 1024x768 (limitation of jpeg parser into coreboot that is not matching seabios's codebase (14 years old...)
- jpeg needs to be exported from with GIMP at 1024x768 using the recommended progressive disabled 4:2:0 (scroll down at end of post https://puri.sm/posts/librem-13-coreboot-report-february-25th-2017/ )

**Comment by tlaurion** [comment]
@thrillatplay that also resolves one of your old issue for your coreboot logo project :)

**Comment by Thrilleratplay** [comment]
@tlaurion I never cross-linked the same problem I listed in Thrilleratplay/coreboot-builder-scripts#15 but I think this [open coreboot PR](https://review.coreboot.org/c/coreboot/+/42806) fixes the issue within the coreboot build.

**Comment by Thrilleratplay** [comment]
A long time ago I remember serendipitously searching for something related the Heads ROM and coming across an image for Janus.

![image](https://github.com/osresearch/heads/assets/553624/63adf568-d56d-4a68-a72d-8ffad5881abf)
[source](https://commons.wikimedia.org/wiki/File:Janus_coin.png)

From [wikipedia](https://en.wikipedia.org/wiki/Janus)
> In ancient Roman religion and myth, Janus is the god of beginnings, gates, transitions, time, duality, doorways, passages, frames, and endings.

@osresearch mentioned that is was also the name of a super computing cluster he used in college.  (Sorry if I misremember any detail)

**Comment by tlaurion** [comment]
> @tlaurion I never cross-linked the same problem I listed in [Thrilleratplay/coreboot-builder-scripts#15](https://github.com/Thrilleratplay/coreboot-builder-scripts/issues/15) but I think this [open coreboot PR](https://review.coreboot.org/c/coreboot/+/42806) fixes the issue within the coreboot build.

@Thrilleratplay no, this is different. this is coreboot's libgfxinit, doing bootsplash just like where your attempts failed. Not seabios jpg/bmp issue. Limitation is that jpeg parser is old and only deal properly with old combination of resolution; this is 1024x768, not native resolution (and why you have empty space left and right of the picture and on the framebuffer after). That would deserve fixing upstream.

**Comment by ThePlexus** [comment]
Hello team

I thought about this a little bit and would like to submit one for consideration. Ive not really done design or symbolism before so I don't expect this to be much liked, but i thought I would try my hand at it. Whats the worst that can happen ;) 

The stylised H circled at the top is designed to represent binary 011 - to show the triad of Heads, Coreboot and Linuxboot together, 

The design also nods to the requirement of including the logos of both coreboot and linuxboot, which handily also represent the triad in the form of a three sided dice

The dice motif is also a nod to QubesOS (cos, well .... of course I would)

And what security thing isnt complete without the shield in 2023?

The backing for this was [SVG shield/dice](https://game-icons.net/1x1/delapouite/dice-shield.html ) which is released under CC 3.0 

the format is JPEG, exported from with GIMP at 1024x768 using the recommended progressive 4:2:2 

![heads-logo](https://github.com/osresearch/heads/assets/31340423/d8096768-fdfd-4ff5-a8db-74559bb72796)

**Comment by tlaurion** [comment]
@ThePlexus as of now you have my vote!

**Comment by walterchris** [comment]
I like the idea @ThePlexus . IMO I would leave out the shield and concentrate more on the "dice" itself. You have to imagine: " How does the logo look on a sticker" and how does it look on a boot screen ?

In both cases IMO it has too many details if you are relying on the shield. Imagine the logo to be printed as-is on a 4inch x 4inch sticker. The outline would be the shield, then the dice itself would be tiny :) 

Other than that it's a great idea :)

**Comment by ThePlexus** [comment]
> I like the idea @ThePlexus . IMO I would leave out the shield and concentrate more on the "dice" itself. You have to imagine: " How does the logo look on a sticker" and how does it look on a boot screen ?
> 
> In both cases IMO it has too many details if you are relying on the shield. Imagine the logo to be printed as-is on a 4inch x 4inch sticker. The outline would be the shield, then the dice itself would be tiny :)

Good points - heres an inverted version, no shield. 

> Other than that it's a great idea :)
Thanks!

![headslogo-noshield](https://github.com/osresearch/heads/assets/31340423/d936b08d-9eff-43af-bda9-fd38b3801361)

**Comment by walterchris** [comment]
I like that much better. Great!

**Comment by d-wid** [comment]
@ThePlexus Is there a (good) way to make the H look like a couple of faces to make it look like Janus as @Thrilleratplay suggested?

**Comment by d-wid** [comment]
Like some less rudimentary version of 
![image](https://github.com/osresearch/heads/assets/65876951/7b5c487f-ad7f-4214-a2e8-41cb5d98dbf6)

**Comment by d-wid** [comment]
I am quite partial of what @Thrilleratplay did with his coreboot logo.
![untitled](https://github.com/osresearch/heads/assets/65876951/189569b6-db6e-41d8-b1ae-6fce3d28a032)

**Comment by tlaurion** [comment]
Two things here and I'm sorry we are currently mixing thing.

- Heads logo
- Heads bootsplash

I think we have something with the H here (Janus Double heads) here for Heads logo, being separated of linuxboot and coreboot.

For Heads bootsplash, I have to say I am fan for the 3 equal parts of dice (representing indirectly Qubes) being sitting on Heads (top) which is a linuxboot  derivative (linux in firmware) sitting on coreboot.

If there was a 3 equal parts of that design, I would take that as a bootsplash today.

**Comment by d-wid** [comment]
> If there was a 3 equal dice parts of that Hackerish design, I would take that as a bootsplash today for myself, simply because I would love to see that at each boot :). But for everyone using Heads by default, I do not know.

> As for Hacker/enthusiasts bootspash vs production ready bootsplash and or derivatives, I think a lot of variations could sit in a separate directory for enthusiasts to choose from at compilation time, but I would prefer if the one referred to/included by default in roms was the most professional looking one (as opposed to hacker enticing?

Leaving this discussion aside,
![heads](https://github.com/osresearch/heads/assets/65876951/0905cd32-eda4-498b-876e-491e6738b88a)

**Comment by tlaurion** [comment]
Will add the two dices under https://github.com/osresearch/heads/pull/1403

With references to authors

**Comment by tlaurion** [comment]
@d-wid @ThePlexus 

I have been having my tests boot up with all your logos
- https://github.com/osresearch/heads/issues/1402#issuecomment-1545404715 (sober)
- https://github.com/osresearch/heads/issues/1402#issuecomment-1546395983 (Janus related)

I do not know if i'm asking too much here, but what about we replace the concept of Janus with two sides of a brain, doing the H of Heads as a logo, and then integrate it in the bootpslash?

I never played around with graphic AI, but if there are people out there willing to do that, I am planning on using @ThePlexus logo under #1061 as a start until we come up with something we want to stick as Heads logo. I love Janus, but it seems not enough serious. I love the H of @ThePlexus, but using that H alone as a logo would be a bit boring. I'll spin that on matrix so see what happens next.

**Comment by tlaurion** [comment]
Well. I was not so successful with AI generators, spending way too much of my night on it yersterday trying to communicate my need with AI.

What went up with the Janus idea is the following but not so convinced
![IMG_0542](https://github.com/osresearch/heads/assets/827570/54615743-243a-4454-8fb3-e522c4b7c973)

**Comment by tlaurion** [comment]
@verygreen shared an interesting idea at DAG#2
> publicly available binaries should have splashscreen with link to donation (qrcode?)

I would try to play with that concept and have a small down right qr code saying:
 "Please donate as much as you can at https://opencollective.com/insurgo"

Not a marketing guy here. Advices welcome.

**Comment by tlaurion** [comment]
![_95efc4a9-bf37-44b0-9525-bbaab39ca946.jpeg](https://github.com/osresearch/heads/assets/827570/1e954295-c9de-49ab-964f-9f6be8132f54)

Logo proposition please thumb 👍👎

**Comment by tlaurion** [comment]
![_9cfd3af5-c523-42d6-95f6-2a81e60f46e4.jpeg](https://github.com/osresearch/heads/assets/827570/588259e7-b08f-43ad-9210-74bb0ae9505e)

Please 👎👍

**Comment by tlaurion** [comment]
![_0e5f0cbe-9adc-4b6c-b5e0-75fc99195f57.jpeg](https://github.com/osresearch/heads/assets/827570/8121fe8d-5653-4566-a384-a5ce2d85427a)

Please 👍👎

**Comment by tlaurion** [comment]
![_66a65c1d-335c-4a56-836b-8a525a8d83ae.jpeg](https://github.com/osresearch/heads/assets/827570/5466b8fc-642f-49bb-b9dc-a40d8389bae0)

Please 👍👎

**Comment by tlaurion** [comment]
![_0e5f0cbe-9adc-4b6c-b5e0-75fc99195f57.jpeg](https://github.com/osresearch/heads/assets/827570/75d323c1-40be-4dd3-ab42-7b0ce4db70cc)

Please 👍👎

**Comment by tlaurion** [comment]
> ![_66a65c1d-335c-4a56-836b-8a525a8d83ae.jpeg](https://github.com/osresearch/heads/assets/827570/5466b8fc-642f-49bb-b9dc-a40d8389bae0)
> 
> Please 👍👎

I'll try to find time to remove text on this one. My personal favorite in respect to Janus

**Comment by tlaurion** [comment]
> > ![_66a65c1d-335c-4a56-836b-8a525a8d83ae.jpeg](https://user-images.githubusercontent.com/827570/258235360-5466b8fc-642f-49bb-b9dc-a40d8389bae0.jpeg)
> > Please +1-1
> 
> I'll try to find time to remove text on this one. My personal favorite in respect to Janus

Tried under https://github.com/osresearch/heads/pull/1451#issue-1837074610 but please modify as you want. Maybe black and white under splashscreen?

**Comment by natterangell** [comment]
This is by far my personally preferred suggestion so far.

> ![heads](https://user-images.githubusercontent.com/65876951/238147111-0905cd32-eda4-498b-876e-491e6738b88a.jpg)

**Comment by tlaurion** [comment]
> This is by far my personally preferred suggestion so far.
> 
> > ![heads](https://user-images.githubusercontent.com/65876951/238147111-0905cd32-eda4-498b-876e-491e6738b88a.jpg)
> 
> 

You would see that being on everyone bootsplash? I like Janus reference but I'm not sure the double headed H fits the need for a logo, nor thr matrix background fit the bootsplash bill, but I could be wrong? 

@natterangell thoughts?

Otherwise I could switch it in a PR and see people's reactions. It's hard to gage those sort of things, so many users are silent voters.

**Comment by natterangell** [comment]
@tlaurion well I'm far from being a graphics designer, so my taste might not be everyone's cup of tea. But I like this logo because it incorporates the janus face (btw, heads as in "the other side of tails", is an interesting reference, given that flipping coins goes back to ancient Rome, and the janus logo was found on several Roman coins).

I like the matrix/techy background, I think it fits well with the underlying technical philosophy behind this project. "The hidden code in the otherwise unknown firmware underpinning our daily computer use" kind of thing. But maybe that's just me.

I'd love to see this in a PR, but I'm a happy camper either way. 

FWIW, I've been thinking it would be nice to have an option for a somewhat "silent boot" process too. I have little need for PCR-values and kernel args on every boot once everything is set up and as long as there are no resigning needed etc. Like plymouth or the old framebuffer consoles where you can hit Esc to see whats going on underneath if you want to. I currently use "console=tty2", so "Finalizing chipset" is the last thing I see before my desktop shows.

**Comment by d-wid** [comment]
@natterangell I think @tlaurion already has that jpg in master (or did at some point). It's not the default splash image but a little symlink manipulation should do it.

**Comment by tlaurion** [comment]
> @natterangell I think @tlaurion already has that jpg in master (or did at some point). It's not the default splash image but a little symlink manipulation should do it.

Exactly. I would like to not fill the git repo with binary images too much but as of now some are under the blobs directory and the coreboot configs point to a symlink that points to @ThePlexus version. That symlink file can point to any other to be used, with master now dealing with jpg voodoo automagically since a patch was added to coreboot requiring imagemagik as an additional host dependency

**Comment by tlaurion** [comment]
@d-wid @natterangell #1501

**Comment by natterangell** [comment]
@tlaurion @d-wid Thanks, I didn't notice the picture was already in master. A new symlink was all it took, looks absolutely wonderful in my opinion :)

I get that the repo shouldn't be filled up with binary images.

**Comment by d-wid** [comment]
I've added a new PR #1502 with images using the logo from #1451, for anyone interested.

**Comment by irelativism** [comment]
A bit late to this discussion but great logos ussually lack complexity and also have very litle relation to the name utilized itself, also the source of the idea "heads" comes from the inverse of TheIncognitoAmenesicSystem not a literal head. Do belueve the janus heads idea to be solid more options should be explored:
. define main principals behind project
. value that want to be portraited
. overall colour scheme used and aschtetics of the hole thing.

Cherrs irelativism.

Here small sketch on direction one could take:
![Screenshot_20240725-224317](https://github.com/user-attachments/assets/97006075-c7ab-430c-828e-8910dcd8378b)
