### ISSUE TITLE
Linux kernel default initramfs.cpio.xz is not reproducible

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#142]
If there is no `initramfs` bundled with the Linux kernel's `bzImage`, `Kbuild` will generate one that is *not* reproducible. This will cause build hash failures.

**Comment by osresearch** [comment]
We can specify in the `dev.cpio` file from the Heads tree, which has only `/dev/console` in it.  It will be replaced with the actual initrd when coreboot is built, but will ensure that the Linux `bzImage` is reproducible.

**Comment by rofl0r** [comment]
here's how i got it reproducible: (this is after applying the same stuff you already got)
https://github.com/sabotage-linux/sabotage/commit/49fe67072805158c7054bceaa39692d35f06d68b
HTH
