### ISSUE TITLE
Remove x230-maximized-fhd_edp variations from untested edf200e7913c62975a424cfb9dbd579747d0665c works fine 

### ISSUE THREAD

**Issue by tlaurion** [osresearch/heads#1444]
> @tlaurion You can remove x230-maximized-fhd_edp variations from untested,  edf200e7913c62975a424cfb9dbd579747d0665c works fine on my eDP-modded X230.
> Sorry for not being able to test it sooner.

_Originally posted by @pcm720 in https://github.com/osresearch/heads/issues/1421#issuecomment-1641646500_

**Comment by tlaurion** [comment]
>  with eDP 4.0 board and 1440p display.
_Originally posted by @pcm720 in https://github.com/osresearch/heads/issues/1387#issuecomment-1528889281

**Comment by tlaurion** [comment]
> Also note that some participation under https://review.coreboot.org/c/coreboot/+/28950. Better from board owners then from me (where past comments have not led to a merge upstream, meaning I would have to maintain this, which I have no intention of doing so).

_Originally posted by @tlaurion in_ https://github.com/osresearch/heads/issues/1387#issue-1683432943

-----

@n4ru @computer-user123 @Tonux599 @househead @pcm720: Your input is needed under https://review.coreboot.org/c/coreboot/+/28950 so that edp patch is [not maintained downstream under Heads](https://github.com/osresearch/heads/commit/6300dd178a35cbe68bc6587fdf48a210f1437607#diff-d095897000f2c096efcb606e92443332356bd37e0d7fa0f6b6dd4da0b531b25f), but merged upstream under coreboot

**Comment by pcm720** [comment]
I don't mind doing that, I just wish I knew the kind of input they need to merge this patch.
AFAIK, all kits currently sold on AliExpress are using USB HID device to control brightness from OS, only Nitrocaster's kit uses original LVDS connection for brightness control. Other than that, all eDP kits should be essentially the same, so this patch should work for any kit that's tapping into DisplayPort output from the docking connector.
I'm using [eDP V4.0 kit from AliExpress](https://aliexpress.com/item/1005004222503527.html).

**Comment by tlaurion** [comment]
Should close when https://github.com/osresearch/heads/pull/1448 is merged
