### ISSUE TITLE
Document the PCRs

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#146]
How does Heads use the PCRs?

**Comment by geedo0** [comment]
I'd like to help out with this. Is there anything in particular that needs investigating? It's unclear to me whether this issue is about just writing documentation or if it's more digging into the source and reverse engineering Heads' components.

**Comment by osresearch** [comment]
We control all the writes to the PCRs, so it is mostly documentation, although there are some things that need to be fixed in the code as well (such as #13 and #15 as well as #150).

**Comment by osresearch** [comment]
Started on document: http://osresearch.net/Keys (or https://github.com/osresearch/heads-wiki/blob/master/Keys.md for edits)

**Comment by tlaurion** [comment]
@geedo0 : if your help offer is still actual, #150 and #15 would need review!
