### ISSUE TITLE
Naming confusion with other heads

### ISSUE THREAD

**Issue by Kasijjuf** [osresearch/heads#183]
I find it very confusing that there are TWO free software projects BOTH named after a play on words of the OS name Tails. There is this firmware—[Heads](https://trmm.net/Heads)—as well as the OS—[heads](https://heads.dyne.org/about.html)—that aims to be a systemd-free, blob-free replacement for Tails.
I had previously read a description of the former, thinking I was reading new, seemingly contradictory information about the latter. This was before I discovered there where two projects of nearly identical names.
As far as the play on words is concerned, I personally think the OS's use of the name makes much more intuitive sense than that of the firmware.

**Comment by osresearch** [comment]
Naming things is one of the two difficult problems in computer science...

Not ruling out a name change in the future, but I would point out that the other heads started a few months after this one.
