### ISSUE TITLE
Boot menu and grub.cfg parser

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#196]
Right now the path to the boot scripts are hard coded and very specialized to booting Qubes (as mentioned in #192).  For non-Qubes users, for installing a new OS from a USB device or for situations when you want to boot something like Tails (cancelled pull request #191), it would be very useful to have a way to parse the existing `/boot/grub/grub.cfg` file to build a boot menu.

The syntax is very much like `/bin/sh`, so it might be possible to build enough scaffolding to just execute it. The PCRs would have already been extended, so an attacker who controlled the file would not be able to retrieve the disk encryption keys (and the system will very soon be executing code from that device anyway).

**Comment by flammit** [comment]
#200 seems to cover a lot of the functionality required for non-Qubes boot now.  In fact, this works for Qubes boot as well, but you're required to enter the disk password on start.

FYI - to get to feature parity on the qubes-update/qubes-init scheme, the generic mechanism still needs the rollback protection (TPM counters are not used in hashes yet) and TPM secret key management.
