### ISSUE TITLE
Disable the ME

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#26]
What happens if the ME firmware is zeroed out? Does coreboot still start up ok?

**Comment by osresearch** [comment]
This would free up almost 8 MB for payload, allowing the top 4 MB to be "locked" as the fall back firmware.

Initial tests work, although coreboot does report that "`WARNING: ME has bad firmware`". Discussion on the coreoot list: https://www.coreboot.org/pipermail/coreboot/2016-September/082016.html

**Comment by osresearch** [comment]
Maybe we can't disable it, but we can greatly reduce the amount of space it uses: https://www.coreboot.org/pipermail/coreboot/2016-September/082038.html

The flash descriptor can be adjust to reduce the size of the ME region, the BIOS region expanded and many of the problematic ME applications are removed from the ROM.  It's not known what is still in the CPU, but all of the network stack is gone.

**Comment by osresearch** [comment]
For future research, the Huffman encoded blobs can be decoded with http://io.smashthestack.org/me/

**Comment by osresearch** [comment]
Hacker News discussion: https://news.ycombinator.com/item?id=12489544

**Comment by zaolin** [comment]
https://github.com/zaolin/me_cleaner

**Comment by osresearch** [comment]
Additional HN discussion: https://news.ycombinator.com/item?id=13056997

Also on hackaday: http://hackaday.com/2016/11/28/neutralizing-intels-management-engine/

The cleaner scripts look good; I should add the extra code for erasing the LZMA modules so that only the huffman ones remain.
