### ISSUE TITLE
coreboot option table is not used.

### ISSUE THREAD

**Issue by persmule** [osresearch/heads#274]
It seems that coreboot option table is not used in current configs. I do not know whether it is a consideration about security, but it removes the capability about tuning those options. (e.g. to assign more UMA for gpu than default 32MiB)
Enabling both USE_OPTION_TABLE and STATIC_OPTION_TABLE (Load default configuration values into CMOS on each boot) may be a better choice, as it allows these default values stored in CBFS being tuned via nvramtool(1) after building and before flashing.

**Comment by osresearch** [comment]
Is this still relevant? Please re-open if we should enable the option table.
