### ISSUE TITLE
Secret sharing via qr codes

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#31]
The disk keys can be split via secret sharing. Need to write a program to split/combine secrets.

**Comment by zaolin** [comment]
There are some good crypto libs out there which can be used for this purpose: https://botan.randombit.net/

**Comment by osresearch** [comment]
https://github.com/osresearch/ssss implements the underlying secret sharing algorithm and can output the secrets to `qrenc`.  It uses libgmp, which would be an additional 400kb library, so it needs to be ported to use mbedtls instead. https://github.com/osresearch/ssss/issues/1

**Comment by tlaurion** [comment]
@osresearch update?

**Comment by osresearch** [comment]
Haven't gone back to it since 2016... yow, time flies.
