### ISSUE TITLE
x220 config tweeks

### ISSUE THREAD

**Issue by tyranosaurus-hex** [osresearch/heads#314]
Hi just built the latest 0.2.1 on lenovo x220, the config file coreboot-x220.config needed some tweeking in the payload section (to mirror the x230 config) to make it point at the correct location for the bzimg and initrd (in the build/x220 folder).
Also the x220.config file in the /boards folder needed tweeking to point to linux-x230.config.
Appart from these bumps when installing it is all working ace.

**Comment by osresearch** [comment]
Would you generate a diff for the configuration files?  Thanks!
