### ISSUE TITLE
module files should optionally enable their dependencies

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#328]
To avoid the board level configurations from having to track dependencies between modules, the module files should instead contain `CONFIG_FOO ?= y` for all of their depdencies.  That way a board can explicitly say "No" to a dependency, but otherwise it will be included.

**Comment by osresearch** [comment]
Unfortunately it isn't that easy -- the evaluation of `modules-$(CONFIG_FOO) += foo` might have already been evaluated.

**Comment by tlaurion** [comment]
Was fixed
