### ISSUE TITLE
4f5432bb461ad63995afb45aba34534e1d8c3d23 breaks etc/config

### ISSUE THREAD

**Issue by persmule** [osresearch/heads#333]
The method introduced in the commit above generates broken etc/config, in which some item becomes 

`export CONFIG_BOOT_DEV="\"/dev/sda3\""`

causing mounting in later stage fail with "No such file or directory".

**Comment by persmule** [comment]
@flammit

**Comment by osresearch** [comment]
Thanks for the patch
