### ISSUE TITLE
x230-flash.rom recipes are missing

### ISSUE THREAD

**Issue by tlaurion** [osresearch/heads#340]
Since the initial flashing still requires manually flashing the 4mb chip, a configuration file should exist at least o modify board configuration to point to it initially, or create an Makefile option to generate such images.

**Comment by osresearch** [comment]
I've restored them and am doing a clean build to make sure that it works.

**Comment by osresearch** [comment]
This results in a coreboot ROM; I don't have an x230 handy to test it.
