### ISSUE TITLE
Recovery shell should use setsid to allow job control

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#382]
Right now it prints "job control not available" and ^C / ^Z / etc don't work.

**Comment by rminnich** [comment]
That's actually deliberate. If you ever get into recovery shell, there may be LOTS of stuff wrong, like misconfigured kernel, missing CTTY support, etc. So we need a way to function even if all is lost.

In some cases the recovery shell has been run with io to 3f8 ...

**Comment by rminnich** [comment]
but I still agree with you
