### ISSUE TITLE
TPM measurements not done in bootblock

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#4]
The bootblock should measure itself and the next stages.

**Comment by osresearch** [comment]
TPM is not setup in the bootblock, but the romstage does enable it with this patch: https://github.com/osresearch/coreboot/commit/716a7328e2cfd84ace3ef901da6fe3e71dbf89ed

**Comment by tlaurion** [comment]
Please neglect above reference; issue 119 is not linked to issue 4.
