### ISSUE TITLE
Build Linux in parallel to reduce build time

### ISSUE THREAD

**Issue by paulmenzel** [osresearch/heads#410]
It looks like with commit 9c95b4ed (Merge branch 'usb-scan-gui' of https://github.com/kylerankin/heads), that currently Linux is not build in parallel, so it takes a long time.

**Comment by osresearch** [comment]
I'm seeing a parallel build on my machine, so I'm not sure if this was fixed in an intermediate commit or if there is something different on yours.  Feel free to re-open if this is still happening.
