### ISSUE TITLE
How to only build `initrd.cpio.xz`?

### ISSUE THREAD

**Issue by paulmenzel** [osresearch/heads#418]
When I do not want to build coreboot and only the `initrd.cpio.xz`, how can I do that? The command below doesn’t work for me.

    make BOARD=qemu-coreboot build/qemu-coreboot/initrd.cpio.xz

**Comment by osresearch** [comment]
```
make BOARD=qemu-coreboot `pwd`/build/qemu-coreboot/initrd.cpio.xz
```

The problem is that the `$(build)` var includes the full path, so it needs to be specified.  We should add an easy target to build the initrd.

(note that if your system `make` is not new enough, you'll need to run `./build/make-4.2/make` instead)

**Comment by paulmenzel** [comment]
Thank you. Your command works.
