### ISSUE TITLE
rpm5.org does not resolve

### ISSUE THREAD

**Issue by paulmenzel** [osresearch/heads#421]
No idea, if this is temporary or not, but currently the build fails, because the Popt download domain is not resolvable.

    modules/popt:popt_url := http://rpm5.org/files/popt/$(popt_tar)

    $ host rpm5.org
    Host rpm5.org not found: 3(NXDOMAIN)

**Comment by paulmenzel** [comment]
The Linux From Scratch server has a copy.

    $ grep url modules/popt
    popt_url := ftp://anduin.linuxfromscratch.org/BLFS/popt/$(popt_tar)

**Comment by osresearch** [comment]
We could also download it from https://github.com/devzero2000/POPT/archive/popt-1_16-release.tar.gz

Is there a more authoritative release?

**Comment by osresearch** [comment]
That github link "works", although it is frustrating that the directory name is bonkers and the "1_16-release" does not match the rpm5 "1.16" release.  They are almost the same, but differ in some test files and random stuff like `.cvsignore`.

funnily enough, rpm5 DNS issues caused a macports bug back in *2007*, so this is a long standing issue: https://trac.macports.org/ticket/29301

And here is some background on *WTF is rpm5?* http://www.internetnews.com/dev-news/article.php/3720556/RPM+5+a+Fork+in+The+Linux+Packaging.htm

**Comment by osresearch** [comment]
Fixed using the http instead of ftp since my corporate firewall blocks FTP.
