### ISSUE TITLE
Error Compiling (Porting to Thinkpad T430)

### ISSUE THREAD

**Issue by flawedworld** [osresearch/heads#442]
So I've been trying to get this running on my T430, but have hit a brick wall. To me it looks like a compiler error. But am not sure.

-----
make -C "/home/user/dev/heads/build/coreboot-4.7/t430" -C /home/user/dev/heads/build/coreboot-4.7 obj=/home/user/dev/heads/build/coreboot-4.7/t430 DOTCONFIG=../../config/coreboot-t430.config BUILD_TIMELESS=1 CFLAGS_x86_32=-fdebug-prefix-map=/home/user/dev/heads=heads -gno-record-gcc-switches CFLAGS_x86_64=-fdebug-prefix-map=/home/user/dev/heads=heads -gno-record-gcc-switches 
make[1]: Entering directory '/home/user/dev/heads/build/coreboot-4.7'
    GEN        generated/bootblock.ld
    CP         bootblock/arch/x86/bootblock.ld
    LINK       cbfs/fallback/bootblock.debug
    OBJCOPY    cbfs/fallback/bootblock.elf
    OBJCOPY    bootblock.raw.bin
    CC         romstage/lib/tlcl.o
src/lib/tlcl.c:196:10: error: no previous prototype for 'tlcl_define_space' [-Werror=missing-prototypes]
 uint32_t tlcl_define_space(uint32_t index, uint32_t perm, uint32_t size)
          ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:337: t430/romstage/lib/tlcl.o] Error 1
make[1]: Leaving directory '/home/user/dev/heads/build/coreboot-4.7'
make: *** [Makefile:356: /home/user/dev/heads/build/coreboot-4.7/t430/.build] Error 1
-----

My qubes config is copy paste from the x230, so is my linux config, im using my own coreboot config (It's been setup as in the wiki). Attached is these files. I'm using 'make BOARD=t430 CPUS=4' to build. Thanks in advance.
[config files.zip](https://github.com/osresearch/heads/files/2345314/config.files.zip)

**Comment by tlaurion** [comment]
Updates given through slack channel on this issue:
rminnich [11:23 AM]
```
coreboot problem
seems it needs CONFIG_TPM2 or CONFIG_TPM1
See if they are in your .config
```

@zaolin [11:39 AM]
```
MAINBOARD_HAS_TPM1 or MAINBOARD_HAS_TPM2 in the mainboard kconfig including MAINBOARD_HAS_{LPC,SPI,I2C}_TPM
```

**Comment by rminnich** [comment]
do you see either CONFIG_TPM1 or CONFIG_TPM2 in .config?

**Comment by flawedworld** [comment]
The laptop is equipped with TPM 1.2

CONFIG_TPM of any sort was not in the .config

I added CONFIG_TPM1=y

The following was present:

CONFIG_MAINBOARD_HAS_LPC_TPM=y

I continue to get the error with CONFIG_TPM1=y

Am going to experiment with TPM2 related flags.

**Comment by flawedworld** [comment]
hmm, everytime  I compile it it resets the .config to how it was.

**Comment by flawedworld** [comment]
Ok I must have screwed up big time everytime I restart the make it just resets the coreboot-t430.config

**Comment by flawedworld** [comment]
Ok, so if I go to config.h in the T430 folder in the coreboot-4.7 folder (AKA the build folder for coreboot) and change CONFIG_TPM 0 to CONFIG_TPM 1 it compiles perfectly. from then on. I now have another error, which I'll paste from my dev machine in a second

**Comment by rminnich** [comment]
https://review.coreboot.org/#/c/coreboot/+/28428/

**Comment by rminnich** [comment]
if you change .config at all, you really need to run
make oldconfig
just to be sure it will stick.

**Comment by flawedworld** [comment]
Got it! So thats been sorted, I now have this new error

`make -C "/home/user/dev/heads/build/coreboot-4.7/t430" -C /home/user/dev/heads/build/coreboot-4.7 obj=/home/user/dev/heads/build/coreboot-4.7/t430 DOTCONFIG=../../config/coreboot-t430.config BUILD_TIMELESS=1 CFLAGS_x86_32=-fdebug-prefix-map=/home/user/dev/heads=heads -gno-record-gcc-switches CFLAGS_x86_64=-fdebug-prefix-map=/home/user/dev/heads=heads -gno-record-gcc-switches 
make[1]: Entering directory '/home/user/dev/heads/build/coreboot-4.7'
    GEN        generated/bootblock.ld
    CP         bootblock/arch/x86/bootblock.ld
    LINK       cbfs/fallback/bootblock.debug
    OBJCOPY    cbfs/fallback/bootblock.elf
    OBJCOPY    bootblock.raw.bin
    CREATE     t430/mainboard/lenovo/t430/cbfs-file.3Za2Sv.out (from ./../../config/coreboot-t430.config)
make[1]: *** No rule to make target 'bzImage', needed by 't430/coreboot.pre'. Stop.
make[1]: Leaving directory '/home/user/dev/heads/build/coreboot-4.7'
make: *** [Makefile:356: /home/user/dev/heads/build/coreboot-4.7/t430/.build] Error 1
`

So what do?

**Comment by zaolin** [comment]
Yo please use the coreboot master instead of version 4.7 which is not working....

**Comment by flawedworld** [comment]
@zaolin How can I do that? when I ran make it auto downloaded coreboot 4.7? I'm using the master branch of heads?

**Comment by zaolin** [comment]
Then heads needs to be updated at least to 4.8.1 but to be honest even if you try reproducible builds. Don't use coreboot release version. Just use a tag you can update.

**Comment by flawedworld** [comment]
Ignore me, I figured out how to put in coreboot 4.8.1 via editing coreboot in the modules folder.

**Comment by flawedworld** [comment]
UPDATE: I have (or at least it seems to be) the same error as I last mentioned

@zaolin Coreboot 4.8.1 did not help

>
make[1]: *** No rule to make target 'bzImage', needed by 't430/coreboot.pre'. Stop.
make[1]: Leaving directory '/home/user/dev/heads/build/coreboot-4.8.1'
make: *** [Makefile:356: /home/user/dev/heads/build/coreboot-4.8.1/t430/.build] Error 1


So close yet so far :/

@tlaurion @rminnich @zaolin Any ideas?

**Comment by flawedworld** [comment]
All sorted had to shift some files around

**Comment by paulmenzel** [comment]
Am 03.09.2018 um 22:55 schrieb flawedworld:
> All sorted had to shift some files around

Nice. Are you going to create a merge/pull request for this device?

If not, could you please document your steps here, so that others with 
similar issues could find your solutions?

**Comment by flawedworld** [comment]
@paulmenzel I am currently trying to debug the rom, as I keep getting artifacts, I forked the project and will do a pull request when I sort it.
