### ISSUE TITLE
Thinkpad T430 Not giving screen output / artifacted screen

### ISSUE THREAD

**Issue by flawedworld** [osresearch/heads#444]
The above occurs no matter how I init the graphics in coreboot? What could have gone wrong?

**Comment by paulmenzel** [comment]
On 09/04/18 10:52, flawedworld wrote:
> The above occurs no matter how I init the graphics in coreboot? What
> could have gone wrong?

Does it work if you built coreboot yourself and use another payload
like GRUB or SeaBIOS?

**Comment by flawedworld** [comment]
Yea, I have been using Tianocore and Coreboot for about a month now

**Comment by flawedworld** [comment]
@paulmenzel the coreboot IRC said that it may be Linux config related? Maybe try another driver?

**Comment by flawedworld** [comment]
Solved, will make an issue describing everything I had to do then will pull request
