### ISSUE TITLE
sealfile2 will not seal a file larger than 128 bytes

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#45]
Spec says 256 bytes should be sealable.

**Comment by zaolin** [comment]
Makes sense the most tpm keys are only 2048bit ;)

**Comment by zaolin** [comment]
You won't find a tpm 1.2 with 4096bit keys. But maybe you can improve their implementation to make use of hybrid cryptography and pre-encrypt via symmetric algo

**Comment by osresearch** [comment]
I realized that I was off by a factor of 8 -- we only need to seal 256 bit symmetric keys, so 32 bytes is plenty.
