### ISSUE TITLE
circleci status on main page

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#456]
We should display the circleci status and last hashes on the mainpage

**Comment by rjoleary** [comment]
You can put this into the README to show the build status:

[![Build
Status](https://circleci.com/gh/osresearch/heads/tree/master.png?style=shield)](https://circleci.com/gh/osresearch/heads/tree/master)

```
[![Build
Status](https://circleci.com/gh/osresearch/heads/tree/master.png?style=shield)](https://circleci.com/gh/osresearch/heads/tree/master)
```

**Comment by tlaurion** [comment]
@osresearch : That would be awesome. With artifact downloads :)

Is there other deployed CI? I know of the following ones:
https://gitlab.com/nemanjan00/heads-ci/-/jobs
https://circleci.com/gh/osresearch/heads
