### ISSUE TITLE
[Question] What tools do you use to install/test heads

### ISSUE THREAD

**Issue by pahakalle** [osresearch/heads#466]
To feed my curiosity i would like to know what tools do you use to install/test heads?

**Comment by tlaurion** [comment]
@pahakalle 
[Documentation is here](http://osresearch.net/). Specifically:
> To feed my curiosity i would like to know what tools do you use to install
[Installing Heads](https://github.com/osresearch/heads-wiki/blob/master/Installing-Heads.md) 
> /test heads?
[Emulating Heads](https://github.com/osresearch/heads-wiki/blob/master/Emulating-Heads.md)
