### ISSUE TITLE
Feature Request: Dynamically set boot partition

### ISSUE THREAD

**Issue by itay-grudev** [osresearch/heads#489]
It would be useful to set the boot partition dynamically the first time Heads is run. A simple wizard can guide you through the process of selecting the boot partition. After you are ready Heads re-flashes updating it's `/etc/fstab`.

For USB boot we scan available disks and allow booting from an arbitrary device.

#### Advantages:
* You won't need to edit board configuration files 
* Building will be deterministic since it no longer depends on a changing board configuration files.
* Less likely to complicate the heads installation if you make a typo.
* Since board configuration file is no longer required a simple board recognition script would be sufficient and building `heads` will be just: `make` **_*_**

---
**_*_** _As long as the blob download/extract scripts are automatic._

**Comment by tlaurion** [comment]
@itay-grudev : implemented in #494 and merged.
