### ISSUE TITLE
Possible T430 Port

### ISSUE THREAD

**Issue by JeffreyAbbinante** [osresearch/heads#506]
I might be buying a T430 soon. So, I will try and help port heads to the T430. Assuming I actually follow through on the purchase. If not, I think this is still a good idea and people should be working on it. It should be similar to the X230.

**Comment by SebastianMcMillan** [comment]
Port has been made, but is untested. Feel free to test T430 on my repo.

**Comment by tlaurion** [comment]
@JeffreyAbbinante @SebastianMcMillan : PR welcome based on https://github.com/osresearch/heads/commit/21faf524b9d791a75f1710ada502f21298b8fa77

**Comment by tlaurion** [comment]
#t430
