### ISSUE TITLE
LibremKey depends on CMake 3.10 where debian-9 provides 3.7

### ISSUE THREAD

**Issue by tlaurion** [osresearch/heads#532]
Changing manually build/libremkey-hotp-verification/CMakeLists.txt:
`cmake_minimum_required(VERSION 3.10)`
to
`cmake_minimum_required(VERSION 3.7)`

Works.

**Comment by kylerankin** [comment]
If downgrading the minimal version works, I'm personally fine with the change.

**Comment by tlaurion** [comment]
Please approve here: https://github.com/Nitrokey/nitrokey-hotp-verification/pull/7

**Comment by tlaurion** [comment]
Fixed with https://github.com/Nitrokey/nitrokey-hotp-verification/pull/7
