### ISSUE TITLE
pinentry compilation failure

### ISSUE THREAD

**Issue by heads105** [osresearch/heads#552]
The only package that doesn't build on Fedora 30 beta is pinentry. If I ./configure in the pinentry using the host configuration, then it builds fine, but it doesn't build under the heads config.

First error is:
pinentry-gtk-2.c:28:28: fatal error: gdk/gdkkeysyms.h: No such file or directory
Followed by a whole set of similar issues once I solved that by hard-coding the gdk location  which natively would be provided by pkg-config --cflags gdk-2.0, I get other similar missing include files.

Should there be a gdk-2.0.pc file or similar in heads/install/lib/pkgconfig/ too?

**Comment by heads105** [comment]
Perhaps this is a sufficient fix for modules/pinentry:
 	--disable-pinentry-qt \
+	--disable-pinentry-gtk2 \
+	--disable-pinentry-gnome3 \
 	--disable-pinentry-fltk \

**Comment by tlaurion** [comment]
@heads105 : if that works for you, those two are not necessary for pinentry to function under heads and should be removed, as all non required functions to reduce space.

Confirm that it works please!

**Comment by heads105** [comment]
@tlaurion Yes, I did make that change and it compiled with no errors. I just flashed the rom on my x230 ok, though haven't done any extensive testing yet.

**Comment by tlaurion** [comment]
PR in exchange of credit?:)

**Comment by heads105** [comment]
@tlaurion The credit is all yours. I'm kicking myself for not having found heads before. Please just add the two lines if it doesn't negatively affect anyone else which I don't think it should do as ./configure --disable-foo doesn't give any error so it should work even if gtk2 and/or gnome3 aren't even options in pinentry.

**Comment by tlaurion** [comment]
@heads105 : nope. Credit goes to @osresearch to have started this project, and then to all Heads contributors!

Welcome aboard! Thanks for the fix!
