### ISSUE TITLE
GPG is too large and overkill

### ISSUE THREAD

**Issue by zaolin** [osresearch/heads#57]
Hey,

I plan to replace GPG bei BSD signify because it's too large and the verity roothash
doesn't require any special. So we can throw out GPG and save around 1.5MB
Signify builds without issues under musl libc

**Comment by zaolin** [comment]
See #58 currently WIP

**Comment by osresearch** [comment]
Using the stable `gpgv` 1.4 (part of commit https://github.com/osresearch/heads/commit/5fd9878d28cd05f89551359cc0de1adfb67a310b) the size has gone down dramatically since it doesn't bring in any additional libraries.  `signify` ends up saving about 50KB in the final `initrd`.

**Comment by osresearch** [comment]
As discussed in the PR #58 we'll be sticking with gpgv for now.
