### ISSUE TITLE
[Discussion] x220 ThinkPad | Laptop Support Request

### ISSUE THREAD

**Issue by WorryTheBirds12** [osresearch/heads#598]
**Discussion**: Running Heads on the [ThinkPad x220](https://www.thinkwiki.org/wiki/Category:x220)
**Why?** The x220 is the only decently built modern mechanical keyboard laptop that can run a modern OS. To many users this is a big benefit. 

_______________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/78051738-discussion-x220-thinkpad-laptop-support-request)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=78051738)](https://www.bountysource.com/issues/78051738-discussion-x220-thinkpad-laptop-support-request)

**Comment by Kokokokoka** [comment]
Heads _is_ working on x220.

**Comment by WorryTheBirds12** [comment]
@Kokokokoka If this is the case, then I only see the x230 for installing heads:

http://osresearch.net/Installing-Heads

Please point me in the direction of the installation steps.

**Comment by flammit** [comment]
ICYMI: With the thinkpad-ec firmware mods, the x230 can use the x220 keyboard.

**Comment by Kokokokoka** [comment]
You can follow the build steps of x230, just replace most parts to x220.
One more thing, please, be so kind and read the Coreboot build howto, as you need to extract blobs, cleanup the ME generate ifd decriptor. 
When you've read the wiki (x220 and build how-to), go through the structure of this project. You'll see that there's x220 in the boards directory. Briefly read the main Makefile. you should set board and etc. Yes, this is not easy,
but after having wiki, http://osresearch.net/Installing-Heads, you'll understand how-to build Heads.

**Comment by SebastianMcMillan** [comment]
X220 is supported, but due to lack of testers, severe bugs are present.

**Comment by tlaurion** [comment]
Functional under https://github.com/osresearch/heads/commit/21faf524b9d791a75f1710ada502f21298b8fa77
