### ISSUE TITLE
Help Thinkpad Roms

### ISSUE THREAD

**Issue by alelopezperez** [osresearch/heads#621]
Can someone give me a builded rom for thinkpad T400 and T420.
I've been trying to build heads and I cant; each probblem i solve just leaves another one.

I was trying to find a forum to post this but this is the only means of communication to ask about this.

**Comment by tlaurion** [comment]
T400 is not supported for the moment.

T420 has a pull request but laptop will hang for 50 seconds at each boot and needs development. You can ask for ROM to the developer which created the pull request. Search for issue on the t420 to see details.

The build system has a problem with newer musl, which has its seperate issue which needs resolution to be able to build ROMs.


On November 8, 2019 7:46:14 PM UTC, Ale Lopez <notifications@github.com> wrote:
>Can someone give me a builded rom for thinkpad T400 and T420.
>I've been trying to build heads and I cant; each probblem i solve just
>leaves another one.
>
>I was trying to find a forum to post this but this is the only means of
>communication to ask about this.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/osresearch/heads/issues/621

-- Sent from /e/ Mail

**Comment by alelopezperez** [comment]
with which thinkpad i'll ge the best performance??

**Comment by techge** [comment]
what do you mean by performance? x230 is probably best supported regarding heads

**Comment by alelopezperez** [comment]
thanks
