### ISSUE TITLE
TPM-Reset

### ISSUE THREAD

**Issue by alelopezperez** [osresearch/heads#634]
Hardware: Thinpad X230
After using tpm-set reset i get the warning "srk.pem is not supported" and I rebooted my X230 a lot of times.
The **seal-totp** does generate a qrcode but running **unseal-totp** just returns the error
"Error Decryption failure fro TPM_Unseal"
"Unable to unseal totp secret"

Also in my **/tpm/secret** folder i only have the file **totp.sealed**.

**Comment by tlaurion** [comment]
@alelopezperez : this srk.pem is a warning not an error.

Measurements are invalidated under recovery shell, and need to be done through the GUI. The secret folder is deleted when accessing the recovery console, too. see [here](https://github.com/osresearch/heads/issues/639#issuecomment-570014587)
