### ISSUE TITLE
Running kexec-save-key wiped the only slot remaining

### ISSUE THREAD

**Issue by EDmitry** [osresearch/heads#645]
After running `kexec-save-key -p /boot/ /dev/sda2` the only slot generated by Qubes installation was wiped, and the new key wasn't inserted. Verified with luksDump that all slots are disabled after running the command. I see that from the code it supposed to wipe the slot 1, but I think the reason my main key was in slot 1 is because I change the LUKS password before. That probably inserted a new key in slot 1 and deleted from 0. 

I think `kexec-seal-key` should verify that it's not removing the only slot available.

**Comment by flammit** [comment]
Yeah that's a good catch.  We probably should be using luksRemoveKey instead.

**Comment by tlaurion** [comment]
> Yeah that's a good catch. We probably should be using luksRemoveKey instead.

@flammit: instead of [killslot](https://github.com/osresearch/heads/blob/master/initrd/bin/kexec-seal-key#L66)?

**Comment by tlaurion** [comment]
> After running `kexec-save-key -p /boot/ /dev/sda2` the only slot generated by Qubes installation was wiped, and the new key wasn't inserted. Verified with luksDump that all slots are disabled after running the command. I see that from the code it supposed to wipe the slot 1, but I think the reason my main key was in slot 1 is because I change the LUKS password before. That probably inserted a new key in slot 1 and deleted from 0.
> 
> I think `kexec-seal-key` should verify that it's not removing the only slot available.

@EDmitry : When you change the password for a keyslot without specifying which one to play with, cryptsetup creates a new slot and deletes the old one. So you had noting in slot 0 anymore, and save-key does't validate if slot 0 exists, kills slot 1 and save new key in 1 as instructed. 

Any proposition?

**Comment by EDmitry** [comment]
@tlaurion yes, the password change was needed because of a suspicion that my password was exposed to couch surfing. The drive didn’t have to be re-encrypted.

I think just checking the amount of slots remaining should be enough. The script should abort if there is only one slot remaining at #1.

**Comment by Jetba** [comment]
Came across this as well while setting up my T430.
After installing Debian 10 with defaults using LUKS+LVM and setting up TPM Disk encryption keys I noticed that there is no support for LUKS version 2. Downgrading LUKS to version 1 also moved my key to slot 1, which caused this issue during setup.

A rare occurance but got me confused for a second 😄 One fast Debian reinstall later and making sure I was using slot 0 solved everything.

**Comment by tlaurion** [comment]
Not sure why I cannot tag this issue from #1482, but that PR fixes this. Closing prematurely otherwise won't be closed automatically (Bad Github)

**Comment by tlaurion** [comment]
@EDmitry @Jetba fixed under #1482 
![2023-09-01-173124](https://github.com/osresearch/heads/assets/827570/3c976571-0b77-4c4b-a765-ad1779ad64a5)
