### ISSUE TITLE
Update cryptsetup version to support LUKS2 headers

### ISSUE THREAD

**Issue by flammit** [osresearch/heads#669]
The current version of cryptsetup included in Heads doesn't support LUKS2 headers, which prevents the disk encryption features from working on default encrypted installs of distros like Fedora 31.

**Comment by alex-nitrokey** [comment]
I try to update cryptsetup as e.g. Ubuntu 20.04 is using LUKS2

**Comment by tlaurion** [comment]
Work under #749
