### ISSUE TITLE
can't boot any other distro than Qubes

### ISSUE THREAD

**Issue by 0rb677** [osresearch/heads#686]
ping @tlaurion 
How to  do it correctly. I tried GuixSD/Gentoo/Void/OpenBSD. No luck.

Guix i found this, but i dont try it
https://lists.defectivebydesign.org/archive/html/help-guix/2019-05/msg00002.html
https://github.com/osresearch/heads/issues/531

Gentoo has .xz and .igz kernel. Kexec core stuck at boot process.

OpenBSD dropping to shell. Maybe because heads use only cfg for boot.
```
grub> kopenbsd -r sd0a (ahci0,openbsd1)/bsd
```

Has anyone else tried to boot this?

Ps. Void works :)

**Comment by tlaurion** [comment]
@0rb677 working steps would be awesome for other people encoutering the same issues you described
