### ISSUE TITLE
initrd depends on system libc

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#7]
This makes the builds harder to reproduce and the initrd larger than necessary. uclibc would be a better choice.

**Comment by osresearch** [comment]
Also considering using Alpine Linux in a VM -- #54

**Comment by zaolin** [comment]
So alpine is too much work. Maybe I can try to setup a build environment for the initramfs only in arch linux. Or do you have other suggestions ?

**Comment by zaolin** [comment]
There is also nixos which consists of reproducible binaries only. But it's far away from being stable. Maybe this is a better solution instead of arch linux.

**Comment by osresearch** [comment]
After recent checkins (https://github.com/osresearch/heads/commit/5fd9878d28cd05f89551359cc0de1adfb67a310b) the only remaining system dependencies for libraries are `libc.so` and `ld-linux-x86-64.so` (on ubuntu build, fedora build also brings in `libdl.so`).  Might be time to consider building `libmusl-libc`.
