### ISSUE TITLE
Blank Screen After Internally Flashing x230-hotp-verification

### ISSUE THREAD

**Issue by lsafd** [osresearch/heads#737]
First off I would like to say that I am a relatively new user so please excuse the mistakes that I will probably make.

I am flashing to a x230 and having similar issues to #667. I am using `x230-hotp-verification` as my final payload for the internal flashing. I have previously used `x230` as my final payload and had success, so this is not my first installation. 

Steps:
1. Flash `x230-flash.rom` image to the top chip.
2. Flash 8MB unlocked and me cleaned image to the bottom chip.
3. Boot to heads shell (So far everything is working)
4. Run `mount-usb`.
5. Run `flash.sh -c /media/coreboot.rom` to flash the 12MB `coreboot.rom` image (from `./build/x230-hotp-verification/`).
6. Run `reboot` to reboot. (I have also tried rebooting using the power button.)

I end up with a blank screen, but the green light for the power button turns on and off as expected.

Attached is the `coreboot.rom` file. I have done a clean build and ended up with a `coreboot.rom` file that has the exact same sha256 hash.

Is there any information I could provide or new strategies I could try? I could post images of me running flash.sh if that would help. I am just unsure where to go from here. Any help would be much appreciated.

[rom_file.zip](https://github.com/osresearch/heads/files/4709026/rom_file.zip)

**Comment by tlaurion** [comment]
Will retest tomorrow

On June 3, 2020 9:48:37 PM UTC, lsafd <notifications@github.com> wrote:
>First off I would like to say that I am a relatively new user so please excuse the mistakes that I will probably make.
>
>I am flashing to a x230 and having similar issues to #667. I am using `x230-hotp-verification` as my final payload for the internal flashing. I have previously used the `x230` as my final payload and had success, so this is not my first installation. 
>
>Steps:
>1. Flash `x230-flash.rom` image to the top chip.
>2. Flash 8MB unlocked and me cleaned image to the bottom chip.
>3. Boot to heads shell (So far everything is working)
>4. Run "mount-usb".
>5. Run `flash.sh -c /media/coreboot.rom` to flash the 12MB `coreboot.rom` image (from `/build/x230-hotp-verification/`).
>6. Run `reboot` to reboot. (I have also tried rebooting using the power button.)
>
>I end up with a blank screen, but the green light for the power button turns on and off as expected.
>
>Attached is the `coreboot.rom` file. I have done a clean build and ended up with a `coreboot.rom` file that has the exact same sha256 hash.
>
>Any help would be much appreciated.
>
>[rom_file.zip](https://github.com/osresearch/heads/files/4709026/rom_file.zip)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/osresearch/heads/issues/737
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tlaurion** [comment]
@lsafd still not sure

**Comment by lsafd** [comment]
> Reconsidering what to do from here for the x230-hotp-verification platform, which doesn't compile if we go back to CBFS_REGION of 70000, not having enough space:

@tlaurion Isn't this the issue (From #667)? Do you just mean that you don't yet now how to solve this problem? Is there an older version or commit that I should clone from that is guaranteed to be working for x230-hotp-verification (or something similar)? 

Thanks a ton for looking into this I realize you're pretty busy!

**Comment by tlaurion** [comment]
@lsafd : I will retest, but x230-htop-verification applied on top of https://github.com/osresearch/heads-wiki/blob/master/Clean-the-ME-firmware.md is supposed to work.

**Comment by tlaurion** [comment]
Can you confirm the behavior is still current with latest downloaded rom from [circleci](https://app.circleci.com/pipelines/github/osresearch/heads) ?

Or a clean build 

- `make BOARD=x230-hotp-verification real.clean && rm build/* crossgcc`
- `make BOARD=x230-hotp-verification`

**Comment by AUX234** [comment]
> Can you confirm the behavior is still current with latest downloaded rom from [circleci](https://app.circleci.com/pipelines/github/osresearch/heads) ?
> 
> Or a clean build
> 
> * `make BOARD=x230-hotp-verification real.clean && rm build/* crossgcc`
> * `make BOARD=x230-hotp-verification`

@tlaurion I am having the same issue as @lsafd with a clean build and the latest downloaded rom from circleci

**Comment by tlaurion** [comment]
So it means t430 and x230 are different....

**Comment by AUX234** [comment]
@tlaurion @lsafd I was able to successfully install heads by building coreboot.rom using #748

**Comment by tlaurion** [comment]
Their CBFS region for x230-hotp-verification is `CONFIG_CBFS_SIZE=0x710000` instread of `CONFIG_CBFS_SIZE=0x800000` (https://github.com/osresearch/heads/pull/748/files#diff-540d604c350e8fd52c25559b642795fbR5)

**Comment by lsafd** [comment]
With the changed in #756 I was able to get things working. The only caveat is that about half of the time when I try to boot the screen stays black and my computer beeps loudly at me. However, the main issue has been solved, so I will close this issue.

Thanks a ton!

**Comment by tlaurion** [comment]
@lsafd that is not normal?

**Comment by lsafd** [comment]
I never experienced this problem when using the coreboot.rom file from x230 (as opposed to x230-hotp-verification), so my assumption was that that this is unusual. Also, I may make another issue for some problems related to luks tpm stuff I'm having.

**Comment by tlaurion** [comment]
Fixed under https://github.com/osresearch/heads/commit/30852aa2739e71ed8c2c889cae91ef3995cfe75a
