### ISSUE TITLE
OEM Factory Reset - operation cannot be done while there is no TPM on the motherboard.

### ISSUE THREAD

**Issue by 0rb677** [osresearch/heads#745]
@tlaurion

TEST inventory : KGPE-D16 and Nitrokey Start

![photo_2020-06-09_17-54-17](https://user-images.githubusercontent.com/60626673/84163523-41821e80-aa7a-11ea-930a-4ce84b5bef50.jpg)

![tpm](https://user-images.githubusercontent.com/60626673/84164112-d7b64480-aa7a-11ea-9b13-ad4a1aeece63.JPG)

[link 1](https://github.com/osresearch/heads/blame/master/initrd/bin/oem-factory-reset#L125-L140)
[link 2](https://github.com/osresearch/heads/blob/master/initrd/bin/config-gui.sh#L166-L168)

**Comment by tlaurion** [comment]
@0rb677 Congrats, you found a bug where[ CONFIG_TPM is not validated](https://github.com/osresearch/heads/blame/master/initrd/bin/oem-factory-reset#L125-L140) as everywhere [else in the code base prior to operation](https://github.com/osresearch/heads/blob/master/initrd/bin/config-gui.sh#L166-L168)

**Comment by tlaurion** [comment]
@MrChromebox ?

**Comment by MrChromebox** [comment]
@tlaurion I'd fixed that locally and forgot to push a PR, I'll do that shortly

**Comment by MrChromebox** [comment]
addressed by #747

**Comment by tlaurion** [comment]
@0rb677 : merged into https://github.com/osresearch/heads/pull/472 Please report success/fail!

**Comment by 0rb677** [comment]
@tlaurion  OEM FACTORY RESET can't reset gpg-key, on x220 it works.

**Comment by 0rb677** [comment]
Clear process on x220

![DSC_0201](https://user-images.githubusercontent.com/60626673/84396758-1e38aa00-ac07-11ea-82bb-0d52ee96c13f.JPG)

**Comment by tlaurion** [comment]
> @tlaurion OEM FACTORY RESET can't reset gpg-key, on x220 it works.

@0rb677 
The x220 has CONFIG_TPM=y.
kgpe-d16 has CONFIG_TPM=n

https://github.com/osresearch/heads/blob/cbad9b663724c95508f0eec027841d93c723c006/initrd/bin/oem-factory-reset#L311

Implemented this validation. Screenshots provided, coming from x220, is not testing previous PR.
Which is why it was advised to test new artifact on kgpe-d16 from #472 [artifacts](https://circleci.com/gh/tlaurion/heads/263?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by 0rb677** [comment]
@tlaurion ok re-building.

**Comment by 0rb677** [comment]
@tlaurion 

I dont understand it works with couple of bugs.
Now i attached gpg-card  and external USB to PC when heads initialized. Then quit to shell and lauch oem-reset script.

1. It access to gpg-card
2. It generates oem-key
3. It changes Admin/Pin
4. Exporting key to USB
5. Reading Firmware
6. Adding gerenerate key to current firmware and re-flashing
7. Signed boot files and generate checksums

So it works?

**Comment by 0rb677** [comment]
@tlaurion congrats it done.

**Comment by 0rb677** [comment]
![DSC_0203](https://user-images.githubusercontent.com/60626673/84409319-f1d85a00-ac15-11ea-8ea7-06912e0f6306.JPG)

![DSC_0204](https://user-images.githubusercontent.com/60626673/84409352-fd2b8580-ac15-11ea-8230-43f416f5572b.JPG)

![DSC_0205](https://user-images.githubusercontent.com/60626673/84409364-01f03980-ac16-11ea-8ca4-2a5c1eafecca.JPG)

![DSC_0206](https://user-images.githubusercontent.com/60626673/84409382-087eb100-ac16-11ea-9ac3-35c77dc7e21d.JPG)

![DSC_0207](https://user-images.githubusercontent.com/60626673/84409396-0d436500-ac16-11ea-9329-af7cfa53ef8e.JPG)

![DSC_0208](https://user-images.githubusercontent.com/60626673/84409424-146a7300-ac16-11ea-992e-674f9dfeb0a8.JPG)

![DSC_0208](https://user-images.githubusercontent.com/60626673/84409454-1d5b4480-ac16-11ea-9507-63e7361a15dd.JPG)

![DSC_0209](https://user-images.githubusercontent.com/60626673/84409472-23512580-ac16-11ea-8fa8-fe7cb6f53d8b.JPG)

**Comment by tlaurion** [comment]
I'm confused with things unrelated to this ticket and not sure of your state with contradictory information,

If I recall well, your use case made me create:
boards/kgpe-d16_workstation-usb_keyboard/kgpe-d16_workstation-usb_keyboard.conf

so make `BOARD=kgpe-d16_workstation-usb_keyboard` which on a clear checkout should be at latest commit:
```
git fetch tlaution
git checkout  kgpe-d16_current_working
git reset --hard
git log
```
should show
```
Merge: a3de462 cbad9b6
Author: Thierry Laurion <insurgo@riseup.net>
Date:   Tue Jun 9 13:59:38 2020 -0400

    Merge remote-tracking branch 'mrchromebox/factory_reset_no_tpm' into kgpe-d16_current_working

commit cbad9b663724c95508f0eec027841d93c723c006 (mrchromebox/factory_reset_no_tpm)
```

**Comment by 0rb677** [comment]
@tlaurion can you enjoy to slack?

**Comment by tlaurion** [comment]
> @tlaurion i cant boot from `Default boot Menu` and /boot is signed by oem-key, also rom is signed too.
> 
> ![DSC_0209](https://user-images.githubusercontent.com/60626673/84409472-23512580-ac16-11ea-8fa8-fe7cb6f53d8b.JPG)

If you flashed a new public key, you changed your rom, measurements are now invalid.
You have to:

- Resign your configs
- Set a new boot default

Screenshots are always helpful.

**Comment by 0rb677** [comment]
@tlaurion can you join to channel? It too hard to answer you in so many threads.

**Comment by tlaurion** [comment]
so @0rb677 is having different behaviors when calling the script from command line vs from the GUI. The command line calls are successful, while doing it from the GUI results in this:
https://github.com/osresearch/heads/blob/master/initrd/bin/oem-factory-reset#L66-L68

with `/tmp/gpg_card_edit_output` being empty and uninformative.

@MrChromebox : any idea why GUI calling /bin/oem-factory-reset is different then from console calling it, which is functional?

**Comment by MrChromebox** [comment]
@tlaurion nothing jumps out at me, will have to take a look

**Comment by tlaurion** [comment]
@0rb677 is that still relevant?

**Comment by tlaurion** [comment]
@0rb677 the kgpe-d16 board is now TPM enabled. So if you want a TPM-less board, you will have to disable TPM inside of the board configs on master.

**Comment by tlaurion** [comment]
Please close this issue or tag me back if still relevant.

**Comment by MrChromebox** [comment]
@tlaurion are you still opposed to setting CONFIG_TPM dynamically upon boot as I do in PR #836 ?

**Comment by tlaurion** [comment]
@MrChromebox Im against rubber ducky USB dongle ressembling nitokey/librem key able to sed everything terminal in a glimpse of an eye and make Heads lie about its real state as proposed in that PR, yes.

For TPM being dynamic, I have nothing against that specific part of that PR following your point there.

**Comment by MrChromebox** [comment]
@tlaurion we have in fact many older Librem 13v2/v3 models which do not have a TPM, as well as ones that do. Having a separate board definition for those is a logistical nightmare, because many times the users aren't even aware. I'll resubmit the part of the patch setting CONFIG_TPM dynamically at boot as a separate PR if you agree, otherwise I'll just keep the patch in Purism's tree for now
