### ISSUE TITLE
gpg: no default secret key: No public key when signing /boot

### ISSUE THREAD

**Issue by warawofrd** [osresearch/heads#751]
I am using a Yubikey FIPS on Lenovo x230 and I built from the latest version on master branch.
I've already generated a public/private key combo and installed the public key on the keyring

However, when I attempt to sign the files in the /boot directory (I've already installed Qubes), I get the following errors:

```
gpg: no default secret key: No public key
gpg: signing failed: No public key
gpg: no default secret key: No public key
gpg: signing failed: No public key
gpg: no default secret key: No public key
gpg: signing failed: No public key
/boot: Unable to sign kexec hashes
Failed to sign default config; press Enter to continue.
```

My TOTP token has also never matched, from the very second I imported it into my authenticator. The computer time matches fine, but the code is not matched.

What should I do to fix these issues? Is building and installing from latest the recommended thing to do? Thanks.

**Comment by tlaurion** [comment]
Please retest from master and reopen if still current
