### ISSUE TITLE
Define target `clean` in Makefile

### ISSUE THREAD

**Issue by techge** [osresearch/heads#754]
As mentioned in #752 it would be nice to have a `make clean` to prevent pitfalls while trying to build heads and maybe even for CI later on.

**Comment by tlaurion** [comment]
@techge https://github.com/osresearch/heads-wiki/blame/master/Building.md#L152-L155

Not enough?

**Comment by techge** [comment]
I see. Not sure though, would this clean `install/include` as well?

**Comment by techge** [comment]
Okay, nevermind. Now I am only wondering if `make clean` would be more suitable for dummys :(

**Comment by tlaurion** [comment]
> I see. Not sure though, would this clean `install/include` as well?

```
real.clean:
        for dir in \
                $(module_dirs) \
                $(kernel_headers) \
        ; do \
                if [ ! -z "$$dir" ]; then \
                        rm -rf "build/$$dir"; \
                fi; \
        done
        cd install && rm -rf -- *

```
```

modules.clean:
        for dir in $(module_dirs) \
        ; do \
                $(MAKE) -C "build/$$dir" clean ; \
                rm "build/$$dir/.configured" ; \
        done

```

Per https://github.com/osresearch/heads-wiki/blob/master/Building.md#helpful-targets-and-options
