### ISSUE TITLE
Include structurized into subfolder

### ISSUE THREAD

**Issue by techge** [osresearch/heads#755]
As mentioned in #752 it would be nice to have the header files of the different projects organized in subfolder in `$(INSTALL)/include` like it is done in linux system as well.

**Comment by tlaurion** [comment]
Those are copied under install/include already?

**Comment by tlaurion** [comment]
Sorry, closed by error.
@techge if doing `make BOARD=board real.clean` I do not have your behavior?

**Comment by techge** [comment]
> if doing make BOARD=board real.clean I do not have your behavior?

Need to test, thank you so far anyway.

And regarding the original request here: it was nonesense, my bad. Sorry for that, bad eyes today.
