### ISSUE TITLE
"HOTP: Invalid Code" and "Error PCR mismatch from TPM_Unseal"

### ISSUE THREAD

**Issue by kcortman** [osresearch/heads#780]
Greetings and warm salutations! 

Firstly, I want to express incredible gratitude to the Heads community for the hard work put into this project. It represents both an incredible technological accomplishment and milestone!  

I’ve recently 'given a go' at flashing my X230 after successfully building a local copy of x230-hotp-verification via the osresearch/heads repo, following the Heads build process as described [here](http://osresearch.net/Building).  All went well!  I also have a factory reset NitroKey Pro (reset via the NitroKey App... and have proceeded to setup the pair as "fresh"). 

The issue I’m having (albeit a very important one) is my inability to get HOTP to show anything other than “HOTP: invalid code”.  

Let me first say that I’ve scoured the forums (to date: Heads, Nitrokey, Purism) for what I’m witnessing and can’t seem to figure out what is wrong (and am starting to think hardware or something way 'left field'). ANY suggestions would be incredible : ) !

Without making this post unduly long, my ailment is that after TPM reset and/or TOTP/HOTP reset, I always get "HOTP:invalid code." 

**Procedure:** 
-Successful Heads flash and boot:
![IMG_0265_rotated](https://user-images.githubusercontent.com/68664403/88231273-77164c00-cc63-11ea-99c3-c32794495f4f.jpg)

-Begin "OEM Factory Reset":
![IMG_0251_rotated](https://user-images.githubusercontent.com/68664403/88231342-9614de00-cc63-11ea-87cd-91dd0c83ddc3.jpg)

-Following prompts:
![IMG_0274_rotated](https://user-images.githubusercontent.com/68664403/88237060-f3ae2800-cc6d-11ea-82ff-08af41e2d78e.jpg)

-Select USB at /media/ and continue...
![IMG_0278_rotated](https://user-images.githubusercontent.com/68664403/88233427-30c2ec00-cc67-11ea-8912-b54a05706844.jpg)

-OEM Factor Reset Complete
![IMG_0254_rotated](https://user-images.githubusercontent.com/68664403/88231428-be9cd800-cc63-11ea-8863-1af77c39c8c3.jpg)

-Reboot 

-Generate new HOTP/TOTP secret:
![IMG_0255_rotated](https://user-images.githubusercontent.com/68664403/88231453-cceaf400-cc63-11ea-86eb-5f936bd11206.jpg)

-Follow prompts
![IMG_0258_rotated](https://user-images.githubusercontent.com/68664403/88231478-daa07980-cc63-11ea-81ca-cc112a252e24.jpg)

*At this point, I want to note; that up until now, the NitroKey Pro is blinking "red," but after this initialization (and before I "Press Enter to continue") it begins to blink "green"!  Which seems like a good thing... but then, next I know, it's blinking "red" again at the next screen showing "HOTP: invalid code": 
![IMG_0260_rotated](https://user-images.githubusercontent.com/68664403/88231520-e8ee9580-cc63-11ea-994c-e19d2bea070a.jpg)

**Expected behavior:**
"HOTP: Success"

Please also note, that my hwclock is 'spot on'.  both 'date' and 'hwclock' are right on UTC time so I fairly certain it's not due to drift or anything like that.  Plus, to this point, HOTP is always reading "invalid code" and not just betwixt restarts or somethign like that.  HOTP never, ever, shows "success".  

**Analysis:**
Digging a bit more... I've been playing in the recovery shell, and I've noticed if I use "unseal-totp" or "unseal-hotp," it returns: "Error PCR mismatch from TPM_Unseal" and associated "Unable to unseal TOTP secret" (and 'HOTP secret', respectively). 

Command "seal-totp" always spits out a QRCode.
Command "seal-libremkey" always gives me the the "Error PCR mismatch from TPM_Unseal" 

**Conclusion:** 
An issue with un/sealing TPM; or maybe the PCR isn't read/writing properly?  But, as I am a newbie, I'm lost for explanation.  I've not seen this type of behavior posted in the forum which makes me believe I'm not following instructions properly (always a possibility ; ), or something is  physically broken?  

I want to thank any and all suggestions or explanation that may come from this discussion.  

Any help would be very appreciated.

**Comment by MrChromebox** [comment]
this is expected when building from master, as the libremkey-hotp-verification module needs to be bumped to fix an error. Pull in #761 or #774 to fix and will work as expected

**Comment by tlaurion** [comment]
#761 specifies 
`hotp-verification_version := 5fb260e631b237a298b6dcca47bbd728f2c5ac3a`

#774 specifies version to commit id:
`03a198c418a60c54ef3ec67ea8a9a2d29b675b9b`

**Comment by kcortman** [comment]
Well, I'll be....  Thank you both, MrChromebox and tlaurion. 

**HOTP: Success**
![IMG_0278_rotated](https://user-images.githubusercontent.com/68664403/88346905-08a3bd80-cd39-11ea-8e6e-bf9507545b1f.jpg)

--closed---
