### ISSUE TITLE
Have the GPG factory reset functions propose/default to RSA 4096 bits keys, not 2048

### ISSUE THREAD

**Issue by tlaurion** [osresearch/heads#831]
@alex-nitrokey @MrChromebox : what approach you prefer?

**Comment by MrChromebox** [comment]
@kylerankin's input would be good too

**Comment by alex-nitrokey** [comment]
We are [currently using 3072 bit](https://github.com/osresearch/heads/commit/308df1e92a6bf6386d80e80ee2ac2422a624da28), it should be secure for quite some years and is faster than 4096.
I never created a PR for this as I wasn't sure if this is actually interesting for heads. I you like to include this approach, we are happy to create a PR.

**Comment by alex-nitrokey** [comment]
3072bit is the gnupg default [since version 2.2.22](https://lists.gnupg.org/pipermail/gnupg-users/2020-August/064056.html) btw. That is to say, once we have updated gnupg, no workarround is needed anymore.

**Comment by tlaurion** [comment]
@alex-nitrokey LTS is 2.21. So changing it will need to be manual.

**Comment by alex-nitrokey** [comment]
> @alex-nitrokey LTS is 2.2.21. So changing it to 4096 will need to be done manually prior of generating keys.

Do you want me to create a PR for default 4096 based on our approach?

**Comment by tlaurion** [comment]
@alex-nitrokey I think it would be a good idea. Putting my nose in the script to do the above in the next days

**Comment by tlaurion** [comment]
Oups, wrong ticket. I meant #771

**Comment by MrChromebox** [comment]
I'm sure I'm missing something, but what's the driving force behind this "issue"? Is a 4096-bit key meaningfully better than 2048-bit now, or in the near future?

**Comment by techge** [comment]
> I'm sure I'm missing something, but what's the driving force behind this "issue"? Is a 4096-bit key meaningfully better than 2048-bit now, or in the near future?

That's the point, yes. Many organization are considering 2048-bit not secure enough in the near future (that is, the next years) as processing power increases regularly. So using 3072-bit is recommended for new keys and this is the standard for newer gnupg versions as well.
