### ISSUE TITLE
exit in rescue shell tries to kill init and generates kernel panic.

### ISSUE THREAD

**Issue by Thrilleratplay** [osresearch/heads#833]
If in the recovery shell and no other processes are running, `exit` will throw a kernel panic.

```
Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000200

Kernel Offset: disabled
---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000200
```

I typed it out of habit trying to reenter `gui-init`.  A system reboot is needed at this point.

**Comment by MrChromebox** [comment]
can confirm

**Comment by tlaurion** [comment]
@MrChromebox what would be the solution here, trying to exit a shell in single user mode?
@Thrilleratplay your expected behavior would be?

**Comment by tlaurion** [comment]
On normal system with login manager, that would go back at login in with user if no authentication mechanisms are in place. 
I have no implementation insights hre without complexifying or adding more tool. Even less since normal UX is gui-init so when you are under shell experience, you normally know what you are doing and do not want to "exit". No?

**Comment by MrChromebox** [comment]
> your expected behavior would be?

probably exit the current shell and start a new one

**Comment by tlaurion** [comment]
A loop in init where ash is called might do it

**Comment by Thrilleratplay** [comment]
@tlaurion  I have no preferred expected behavior, anything that allows the user to continue using heads without manually rebooting the machine.

**Comment by MrChromebox** [comment]
> A loop in init where ash is called might do it

unfortunately not: since we exec the recovery shell, there's nothing to exit to. Need to drop the exec, and add a loop. I'll push a PR

**Comment by tlaurion** [comment]
Fixed under https://github.com/osresearch/heads/commit/0eb1f692169f6b833315896f65bdc9587e52624d
