### ISSUE TITLE
cross-musl downloads are not verified

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#97]
No hashes or signatures are checked when the binutils etc are downloaded. Reported upstream: https://bitbucket.org/GregorR/musl-cross/issues/16/tool-chain-tar-file-signatures-or-hashes

**Comment by rofl0r** [comment]
please file your issues on the github mirror. GregorR/musl-cross. the bitbucket repo is unmaintained.

**Comment by rofl0r** [comment]
oh btw, just FYI, there's also [musl-cross-make](https://github.com/richfelker/musl-cross-make) which only supports GCC >= 6, but it does do hash verification.

**Comment by osresearch** [comment]
musl-cross does check hashes now, although musl-cross-make is worth checking out #650
