### ISSUE TITLE
OpenBSD Support for heads?

### ISSUE THREAD

**Issue by FrostKnight** [osresearch/heads#982]
When I get my nitropad and in the not so near future, I wondered if it would be possible to boot OpenBSD FDE (not including encrypted boot)

**Comment by tlaurion** [comment]
Duplicate of #697

**Comment by FrostKnight** [comment]
My bad, but can you answer my reply on #697?
In case you didn't realize, I was speaking of booting OpenBSD or HyperbolaBSD on top of the heads' bios.  
Not meaning to be rude, but yeah, that was what I meant.

I assume though, changes would be needed to be made for any OS based on OpenBSD to be supported by heads right?

**Comment by FrostKnight** [comment]
Btw, HyperbolaBSD won't be out for 3+ years.
