### ISSUE TITLE
not working because of iasl/multiple definition of Asl Compiler Val; Counter Forensics Feature

### ISSUE THREAD

**Issue by wyvern-fairlight** [osresearch/heads#994]
hi, i was going to contribute my first feature, a category of increasingly advanced "counter forensics" techniques, which can optionally be enabled, as subentries, of the Options >> menu. i'm being stopped by something called iasl preceeded by a duplicate reference warning/error in the buildchain. kindly support on getting up to speed with the compile chain / elaborate on why clandestine features would not be desired.
![1](https://user-images.githubusercontent.com/82589131/117623543-75baff00-b163-11eb-9209-1ff17e536ca7.png)
![2](https://user-images.githubusercontent.com/82589131/117623560-79e71c80-b163-11eb-9846-ba77296b6f82.png)

**Comment by tlaurion** [comment]
@wyvern-fairlight @Buom01 have you fixed this issue? Seems like host dependency **_iasl_** was not found on system per required host dependencies needed on debian-10:
`apt install -y build-essential zlib1g-dev uuid-dev libdigest-sha-perl libelf-dev bc bzip2 bison flex git gnupg iasl m4 nasm patch python python2 python3 wget gnat cpio ccache pkg-config cmake libusb-1.0-0-dev autoconf texinfo ncurses-dev doxygen graphviz udev libudev1 libudev-dev automake libtool rsync innoextract`

Please close this issue if resolved.

**Comment by tlaurion** [comment]
The host dependency was not installed

**Comment by AldenIsMe** [comment]
> @wyvern-fairlight @Buom01 have you fixed this issue? Seems like host dependency **_iasl_** was not found on system per required host dependencies needed on debian-10:
> `apt install -y build-essential zlib1g-dev uuid-dev libdigest-sha-perl libelf-dev bc bzip2 bison flex git gnupg iasl m4 nasm patch python python2 python3 wget gnat cpio ccache pkg-config cmake libusb-1.0-0-dev autoconf texinfo ncurses-dev doxygen graphviz udev libudev1 libudev-dev automake libtool rsync innoextract`
> 
> Please close this issue if resolved.

Still having this issue, I ran the command you said, it installed a few extra depends and still comes to same error, I'm trying to compile on Kali Linux WSL.
